
// 2005-04-28 by cmkwon
// #include "StringDefineServer.h"
#ifndef _STRING_DEFINE_SERVER_H_
#define _STRING_DEFINE_SERVER_H_

#include "StringDefineCommon.h"


///////////////////////////////////////////////////////////////////////////////
// 1 Atum
	// 1-1 
	#define STRERR_S_ATUMEXE_0001 "Сервер не отвечает"
	#define STRERR_S_ATUMEXE_0002 "Соединение закрыто сервером!"
	#define STRERR_S_ATUMEXE_0003 "Ошибка автоматического обновления.\r\nПереустановите игру.\r\n"
	#define STRERR_S_ATUMEXE_0004 "ОШИБКА %s(%#04X) получена от %s[%s]\r\n"
	#define STRERR_S_ATUMEXE_0005 "Неизвестная ошибка: %s(%#04x)"
	#define STRERR_S_ATUMEXE_0006 "Соединение с сервером загрузки невозможно."
	#define STRERR_S_ATUMEXE_0007 "Размер скачиваемого файла неизвестен."
	#define STRERR_S_ATUMEXE_0008 "Файл обновления не может быть скачан."
	#define STRERR_S_ATUMEXE_0009 "Не хватает памяти."
	#define STRERR_S_ATUMEXE_0010 "Поврежден .exe файл."
	#define STRERR_S_ATUMEXE_0011 "Файл не найден."
	#define STRERR_S_ATUMEXE_0012 "Указанный путь не найден. "
// 2006-04-20 by cmkwon, 	#define STRERR_S_ATUMEXE_0013 "[Ошибка]Неизвестный тип сообщения: %d(0x%08X)\n"
// 1_end
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// 2 - AtumLauncher
	// 2-1 STRMSG
	#define STRMSG_S_ATUMLAUNCHER_0000 "Обновление завершено"
	#define STRMSG_S_ATUMLAUNCHER_0001 "Выберите сервер"
	#define STRMSG_S_ATUMLAUNCHER_0002 "Обновление списка удаляемых файлов v%s\r\n"
	#define STRMSG_S_ATUMLAUNCHER_0003 "Удаляются временные файлы"
	#define STRMSG_S_ATUMLAUNCHER_0004 "Процесс обновления"
	#define STRMSG_S_ATUMLAUNCHER_0005 "Обновление завершено (%s -> %s)"
	#define STRMSG_S_ATUMLAUNCHER_0006 "Выберите исполняемый файл"
	#define STRMSG_S_ATUMLAUNCHER_0007 "Выберите директорию игры"
	#define STRMSG_S_ATUMLAUNCHER_0008 "Загрузка прервана"
	#define STRMSG_S_ATUMLAUNCHER_0009 "загрузка завершена"
	#define STRMSG_S_ATUMLAUNCHER_0010 "Обновление до версии v%s - %s(%d/%d)"
	#define STRMSG_S_ATUMLAUNCHER_0011 "Невозможно создать файл %s"
	#define STRMSG_S_ATUMLAUNCHER_0012 "Обновление до версии v%s - %s(%d/%d)"
	#define STRMSG_S_ATUMLAUNCHER_0013 "Получение информации о файле %s"
	#define STRMSG_S_ATUMLAUNCHER_0014 "VTCGuard updating"				// 2012-02-09 by hskim, єЈЖ®іІ X-Trap -> VTC °Ўµе·О єЇ°ж
	#define STRMSG_S_ATUMLAUNCHER_0015 "VTCGuard update completed"		// 2012-02-09 by hskim, єЈЖ®іІ X-Trap -> VTC °Ўµе·О єЇ°ж
	
	// STRERR
	#define STRERR_S_ATUMLAUNCHER_0000 "[Ошибка] Parameter Count Error, Count (%d)\n"
	#define STRERR_S_ATUMLAUNCHER_0001 "[Ошибка] Mutex Error\n"
	#define STRERR_S_ATUMLAUNCHER_0002 "[Ошибка] Excute Type Error, Type(%s)\n"
	#define STRERR_S_ATUMLAUNCHER_0003 "[Ошибка] Decryption ID Error, DecryptedID(%s)\n"
	#define STRERR_S_ATUMLAUNCHER_0004 "Невозможно соединиться с Pre сервером"
	#define STRERR_S_ATUMLAUNCHER_0005 "Соединение с сервером неудачно"
	#define STRERR_S_ATUMLAUNCHER_0006 "Соединение сброшено Pre сервером!"
	#define STRERR_S_ATUMLAUNCHER_0007 "Notice File Error!"
//	#define STRERR_S_ATUMLAUNCHER_0008 "Скачайте игру еще раз.\nURL: http://aceonline.ru "
	#define STRERR_S_ATUMLAUNCHER_0009 "Автоматическое обновление неудачно.\r\nПожалуйста, переустановите игру.\r\n"
	#define STRERR_S_ATUMLAUNCHER_0010 "Все сервера недоступны"
	#define STRERR_S_ATUMLAUNCHER_0011 "%-16s%s проверяется..."
	#define STRERR_S_ATUMLAUNCHER_0012 "Сервера недоступны. Попробуйте войти в игру позднее."
	#define STRERR_S_ATUMLAUNCHER_0013 "ОШИБКА %s(%#04X) получена от %s[%s]\r\n"
// 2006-05-26 by cmkwon	#define STRERR_S_ATUMLAUNCHER_0014 "Неверное имя, ошибка пароля\n\n* только люди, со статусом бета-тестеров, способны войти в игру в настоящий момент."
//	#define STRERR_S_ATUMLAUNCHER_0014 "Вы ввели неверное имя или пароль. Введите зарегистрированное имя и пароль."
	#define STRERR_S_ATUMLAUNCHER_0015 "Ошибка входа"
	#define STRERR_S_ATUMLAUNCHER_0016 "Имя пользователя не введено"
	#define STRERR_S_ATUMLAUNCHER_0017 "Двойной вход"
	#define STRERR_S_ATUMLAUNCHER_0018 "Field cервер не запущен."
	#define STRERR_S_ATUMLAUNCHER_0019 "IM cервер не запущен."
	#define STRERR_S_ATUMLAUNCHER_0020 "Работа сервера временно приостановлена.\n\nПопробуйте войти позднее."
	#define STRERR_S_ATUMLAUNCHER_0021 "Сервер перегружен.\n\nПопробуйте войти позднее."
	#define STRERR_S_ATUMLAUNCHER_0022 "Ваш аккаунт заблокирован.\n Срок: %s\n\nОбратитесь по адресу support.4game.ru, для получения более подробной информации."
	#define STRERR_S_ATUMLAUNCHER_0023 "Неверная версия клиента.\n\nПожалуйста, скачайте игру еще раз."
	#define STRERR_S_ATUMLAUNCHER_0024 "ОШИБКА: %s(%#04X)"
	#define STRERR_S_ATUMLAUNCHER_0025 "Не удалось подключиться к серверу загрузки"
	#define STRERR_S_ATUMLAUNCHER_0026 "Размер скачиваемого файла (%s) неизвестен"
	#define STRERR_S_ATUMLAUNCHER_0027 "Размер скачиваемого файла неизвестен"
	#define STRERR_S_ATUMLAUNCHER_0028 "Невозможно скачать файл обновления"
	#define STRERR_S_ATUMLAUNCHER_0029 "Обновленных файлов не существует"
	#define STRERR_S_ATUMLAUNCHER_0030 "Ведутся технические работы. Попробуйте зайти позднее."
	#define STRERR_S_ATUMLAUNCHER_0031 "Не хватает памяти или системных ресурсов"
	#define STRERR_S_ATUMLAUNCHER_0032 "Неверный файл .exe"
	#define STRERR_S_ATUMLAUNCHER_0033 "Файл не найден"
	#define STRERR_S_ATUMLAUNCHER_0034 "Директория не найдена"
// 2006-04-20 by cmkwon	#define STRERR_S_ATUMLAUNCHER_0035 "[ОШИБКА] Недопустимый тип сообщения: %s(%#04X)\n"
// 2006-04-20 by cmkwon	#define STRERR_S_ATUMLAUNCHER_0036 "[ОШИБКА] Недопустимый тип сообщения!\n"

	#define STRMSG_S_050506		"Аккаунт игрока \'%s\' заблокирован.\n  Причина: %s\n Срок: %s~%s\n\n Обратитесь по адресу http://support.4game.ru/ для получения более подробной информации."
	#define STRMSG_S_050930		"Пожалуйста, скачайте игру еще раз.\nURL: %s\nпоследняя версия: "
// 2_end
///////////////////////////////////////////////////////////////////////////////	

///////////////////////////////////////////////////////////////////////////////
// 3 - AtumAdminTool
	// 3-1 STRMSG
//	#define STRMSG_S_SCADMINTOOL_0000 "Мужчина"
//	#define STRMSG_S_SCADMINTOOL_0001 "Женщина"
//	#define STRMSG_S_SCADMINTOOL_0002 "A.D%d, Возраст%d"
//	#define STRMSG_S_SCADMINTOOL_0003 "Вы действительно хотите изменить информацию о вашем аккаунте?"
//	#define STRMSG_S_SCADMINTOOL_0004 "CAST(l.CurrentCount AS VARCHAR(10)) + 'единиц'"
//	#define STRMSG_S_SCADMINTOOL_0005 "CAST(l.ChangeCount AS VARCHAR(10)) + 'единиц получено, ' + CAST(l.CurrentCount AS VARCHAR(10)) + 'единиц'"
//	#define STRMSG_S_SCADMINTOOL_0006 "'''Кому: ' + l.PeerCharacterName + ''', отдано ' + CAST(l.ChangeCount AS VARCHAR(10)) + 'единиц, итого ' + CAST(l.CurrentCount AS VARCHAR(10)) + 'единиц'"
//	#define STRMSG_S_SCADMINTOOL_0007 "'''Кому: ' + l.PeerCharacterName + ''', получено ' + CAST(l.ChangeCount AS VARCHAR(10)) + 'единиц, итого ' + CAST(l.CurrentCount AS VARCHAR(10)) + 'единиц'"
//	#define STRMSG_S_SCADMINTOOL_0008 "'''Удалено ' + CAST(l.ChangeCount AS VARCHAR(10)) + 'единиц, итого ' + CAST(l.CurrentCount AS VARCHAR(10)) + 'единиц'"
//	#define STRMSG_S_SCADMINTOOL_0009 "CAST(l.ChangeCount AS VARCHAR(10)) + 'единиц куплено, осталось SPI: ' + CAST(l.RemainedMoney AS VARCHAR(10))"
//	#define STRMSG_S_SCADMINTOOL_0010 "CAST(l.ChangeCount AS VARCHAR(10)) + 'единиц продано, осталось SPI: ' + CAST(l.RemainedMoney AS VARCHAR(10))"
//	#define STRMSG_S_SCADMINTOOL_0011 "CAST(l.CurrentCount AS VARCHAR(10)) + 'единиц'"
	#define STRMSG_S_SCADMINTOOL_0012 "'''' + l.PeerCharacterName + ''' добавлено ' + CAST(l.ChangeCount AS VARCHAR(10)) + 'единиц, итого ' + CAST(l.CurrentCount AS VARCHAR(10)) + 'единиц'"
	#define STRMSG_S_SCADMINTOOL_0013 "'''' + l.PeerCharacterName + ''' удалено ' + CAST(l.ChangeCount AS VARCHAR(10)) + 'единиц, итого ' + CAST(l.CurrentCount AS VARCHAR(10)) + 'единиц'"
	#define STRMSG_S_SCADMINTOOL_0014 "'Добавить ' + CAST(l.ChangeCount AS VARCHAR(10)) + 'единиц , ' + CAST(l.CurrentCount AS VARCHAR(10)) + 'единиц'"
	#define STRMSG_S_SCADMINTOOL_0015 "'Сдано хранилище ' + CAST(l.ChangeCount AS VARCHAR(10)) + 'единиц, итого ' + CAST(l.CurrentCount AS VARCHAR(10)) + 'единиц'"
	#define STRMSG_S_SCADMINTOOL_0016 "'Получено из хранилища ' + CAST(l.ChangeCount AS VARCHAR(10)) + 'единиц, итого' + CAST(l.CurrentCount AS VARCHAR(10)) + 'единиц'"
	#define STRMSG_S_SCADMINTOOL_0017 "\'Игровое время \' + dbo.atum_GetHMSFromS(l.PlayTime) + \', всего \' + dbo.atum_GetHMSFromS(l.TotalPlayTime)"
	#define STRMSG_S_SCADMINTOOL_0018 "CAST(l.Param1 AS VARCHAR(10)) + ' -> ' + CAST(l.Param2 AS VARCHAR(10)) + ', игровое время: ' + dbo.atum_GetHMSFromS(l.Param3)"
//	#define STRMSG_S_SCADMINTOOL_0019 "CAST(l.Param1 AS VARCHAR(15)) + \' растет и падает, всего \' + CAST(l.Param2 AS VARCHAR(15))"
//	#define STRMSG_S_SCADMINTOOL_0020 "Падение"
//	#define STRMSG_S_SCADMINTOOL_0021 "Монстр"
//	#define STRMSG_S_SCADMINTOOL_0022 "Корабль"
//	#define STRMSG_S_SCADMINTOOL_0023 "Причина неизвестна"
//	#define STRMSG_S_SCADMINTOOL_0024 "%s, осталось очков : %s"
	#define STRMSG_S_SCADMINTOOL_0025 "(Не существует)"
//	#define STRMSG_S_SCADMINTOOL_0026 "Себя"
//	#define STRMSG_S_SCADMINTOOL_0027 "Не существует"
//	#define STRMSG_S_SCADMINTOOL_0028 "Багоюзер"
	#define STRMSG_S_SCADMINTOOL_0029 "Аккаунт заблокирован"
	#define STRMSG_S_SCADMINTOOL_0030 "Общение запрещено"
//	#define STRMSG_S_SCADMINTOOL_0031 "Лог соединения"
//	#define STRMSG_S_SCADMINTOOL_0032 "Лог пользователя"
//	#define STRMSG_S_SCADMINTOOL_0033 "Лог предметов"
	#define STRMSG_S_SCADMINTOOL_0034 "%s - %s сервер"
	#define STRMSG_S_SCADMINTOOL_0035 "%s - %s сервер,%d(%d)"
	#define STRMSG_S_SCADMINTOOL_0036 "Заблокирован"
//	#define STRMSG_S_SCADMINTOOL_0037 "Классификация"
//	#define STRMSG_S_SCADMINTOOL_0038 "Значение"
	#define STRMSG_S_SCADMINTOOL_0039 "Вы хотите разблокировать данный аккаунт?"
	#define STRMSG_S_SCADMINTOOL_0040 "%s(%dсек.)"
	#define STRMSG_S_SCADMINTOOL_0041 "%dwin %dlost"
	#define STRMSG_S_SCADMINTOOL_0042 "Вы действительно хотите выйти и заблокировать аккаунт?"
	#define STRMSG_S_SCADMINTOOL_0043 "%s предмет"
	#define STRMSG_S_SCADMINTOOL_0044 "[%s %15s] Примечание : %s\r\n"
	#define STRMSG_S_SCADMINTOOL_0045 "Кол-во пользователей : %d\r\n"
	#define STRMSG_S_SCADMINTOOL_0046 "[%s %15s] Получено сообщение : %s\r\n"
	#define STRMSG_S_SCADMINTOOL_0047 "[%s %15s] кол-во пользователей : %4d\r\n"
	#define STRMSG_S_SCADMINTOOL_0048 "[%s %15s] состояние FieldServer : %d\r\n"
	#define STRMSG_S_SCADMINTOOL_0049 "Связь с сервером утеряна\nSocket Name: %s\nIP: %s"
	
	// 3-2 AtumAdminTool - STRERR
	#define STRERR_S_SCADMINTOOL_0000 "Невозможно загрузить информацию об аккаунте."
	#define STRERR_S_SCADMINTOOL_0001 "Не удалось изменить информацию об аккаунте."
	#define STRERR_S_SCADMINTOOL_0002 "Введите пароль"
	#define STRERR_S_SCADMINTOOL_0003 "Пароль неверен"
	#define STRERR_S_SCADMINTOOL_0004 "Введите логин"
	#define STRERR_S_SCADMINTOOL_0005 "Pre Server недоступен"
	#define STRERR_S_SCADMINTOOL_0006 "Невозможно соединиться с PreServer!"
//	#define STRERR_S_SCADMINTOOL_0007 "Ошибка авторизации"			// 2006-04-11 by cmkwon, БЦј®Гіё®ЗФ
	#define STRERR_S_SCADMINTOOL_0008 "ОШИБКА: Подходящий протокол не найден."
	#define STRERR_S_SCADMINTOOL_0009 "Введите имя пользователя"
	#define STRERR_S_SCADMINTOOL_0010 "Введите причину"
	#define STRERR_S_SCADMINTOOL_0011 "Ошибка распределения опыта : Уровень %2d ==> Опыт(%.1I64f ~ %.1I64f)"
	#define STRERR_S_SCADMINTOOL_0012 "Максимальный размер лога превышен.\r\n\r\nИзмените максимальный размер лога или условия поиска."
	#define STRERR_S_SCADMINTOOL_0013 "Невозможно подключиться к базе данных"
	#define STRERR_S_SCADMINTOOL_0014 "Нет соединения"
	#define STRERR_S_SCADMINTOOL_0015 "Есть соединение"
	#define STRERR_S_SCADMINTOOL_0016 "Идет обновление"
	#define STRERR_S_SCADMINTOOL_0017 "Залогинился"
	#define STRERR_S_SCADMINTOOL_0018 "Выбор персонажа"
	#define STRERR_S_SCADMINTOOL_0019 "В игре"
	#define STRERR_S_SCADMINTOOL_0020 "Неизвестно"
	#define STRERR_S_SCADMINTOOL_0021 "База данных %s(%s:%d)не может быть подключена"
	#define STRERR_S_SCADMINTOOL_0022 "Не удалось добавить предмет"
	#define STRERR_S_SCADMINTOOL_0023 "Не удалось найти заблокированный аккаунт"
	#define STRERR_S_SCADMINTOOL_0024 "Необходимо заблокировать аккаунт, чтобы изменить его!"
	#define STRERR_S_SCADMINTOOL_0025 "SPI(деньги) невозможно добавить."
	#define STRERR_S_SCADMINTOOL_0026 "Выбранный предмет уже существует, укажите количество."
	#define STRERR_S_SCADMINTOOL_0027 "Не удалось найти предмет"
	#define STRERR_S_SCADMINTOOL_0028 "SPI(деньги), используемые игроком, нельзя удалить."
	#define STRERR_S_SCADMINTOOL_0029 "Вы хотите удалить этот предмет?"
	#define STRERR_S_SCADMINTOOL_0030 "Не удалось удалить предмет"
	#define STRERR_S_SCADMINTOOL_0031 "Не удалось модифицировать предмет"
	#define STRERR_S_SCADMINTOOL_0032 "Введите аккаунт"
	#define STRERR_S_SCADMINTOOL_0033 "Аккаунт не существует (возможно, он заблокирован)"
	#define STRERR_S_SCADMINTOOL_0034 "Аккаунт или персонаж не существует"
	#define STRERR_S_SCADMINTOOL_0035 "Ошибка при поиске информации о персонаже."
	#define STRERR_S_SCADMINTOOL_0036 "Персонаж не найден"
	#define STRERR_S_SCADMINTOOL_0037 "Ошибка при обновлении персонажа"
	#define STRERR_S_SCADMINTOOL_0038 "Информация о персонаже успешно обновлена"
	#define STRERR_S_SCADMINTOOL_0039 "Выберите предмет"
	#define STRERR_S_SCADMINTOOL_0040 "Выберите кол-во предметов"
	#define STRERR_S_SCADMINTOOL_0041 "Можно создать не более 5 ед. предмета."
	#define STRERR_S_SCADMINTOOL_0042 "Введите сообщение"
	#define STRERR_S_SCADMINTOOL_0043 "Примечание не может быть отправлено"
	#define STRERR_S_SCADMINTOOL_0044 "%s: состояние сервера (%d)\r\n"
	#define STRERR_S_SCADMINTOOL_0045 "IM Server не отвечает."
	#define STRERR_S_SCADMINTOOL_0046 "Field Server не отвечает."
	#define STRERR_S_SCADMINTOOL_0047 "[%s %15s] Состояние IMServer : %d\r\n"
	#define STRERR_S_SCADMINTOOL_0048 "ЖДЖ®іКїЎ АеВшµИ јТДП ѕЖАМЕЫ АФґПґЩ.\nјТДПАМ АеВшµИ ЖДЖ®іК јУјєГўїЎј­ »иБ¦°Ў °ЎґЙЗХґПґЩ."
	#define STRERR_S_SCADMINTOOL_0049 "ЖДЖ®іКјУјє єЇ°ж»зЗЧ LogАъАеАМ ЅЗЖР µЗѕъЅАґПґЩ.\r\n(ЖДЖ®іК јУјє єЇ°жАє їП·бµК, Logёё АъАе ЅЗЖР.)"
	#define STRERR_S_SCADMINTOOL_0050 "ЖДЖ®іК Б¤єё ·ОµщАМ ЅЗЖР µЗѕъЅАґПґЩ"
	#define STRERR_S_SCADMINTOOL_0051 "АеВшБЯАО јТДП ѕЖАМЕЫ »иБ¦°Ў ЅЗЖР µЗѕъЅАґПґЩ."
	#define STRERR_S_SCADMINTOOL_0052 "АеВшЗТ јТДП ѕЖАМЕЫАЗ ЗПАМµз їЙјЗ АыїлАМ ЅЗЖР µЗѕъЅАґПґЩ."
	#define STRERR_S_SCADMINTOOL_0053 "ЖДЖ®іК јТДП ѕЖАМЕЫАЗ јцБ¤АМ ЅЗЖР µЗѕъЅАґПґЩ."
	#define STRERR_S_SCADMINTOOL_0054 "ЖДЖ®іК Б¤єё ѕчµҐАМЖ®°Ў ЅЗЖР µЗѕъЅАґПґЩ"
	#define STRERR_S_SCADMINTOOL_0055 "ЖДЖ®іК·№є§ Б¤єё ·ОµщАМ ЅЗЖРµЗѕъЅАґПґЩ"

	// 3-3 AtumLaAtumAdminTool -
//	#define STRMSG_S_SCAT_COLNAME_0000 "Имя аккаунта"
//	#define STRMSG_S_SCAT_COLNAME_0001 "Тип"
//	#define STRMSG_S_SCAT_COLNAME_0002 "история"
//	#define STRMSG_S_SCAT_COLNAME_0003 "Дата начала"
//	#define STRMSG_S_SCAT_COLNAME_0004 "Дата окончания"
//	#define STRMSG_S_SCAT_COLNAME_0005 "Ответственный"
//	#define STRMSG_S_SCAT_COLNAME_0006 "Причина"
//	#define STRMSG_S_SCAT_COLNAME_0007 "Дата"
//	#define STRMSG_S_SCAT_COLNAME_0008 "Тип лога"
//	#define STRMSG_S_SCAT_COLNAME_0009 "IP"
//	#define STRMSG_S_SCAT_COLNAME_0010 "Имя сервера"
//	#define STRMSG_S_SCAT_COLNAME_0011 "Имя персонажа"
//	#define STRMSG_S_SCAT_COLNAME_0012 "Локация"
//	#define STRMSG_S_SCAT_COLNAME_0013 "Описание"
//	#define STRMSG_S_SCAT_COLNAME_0014 "Предмет"
//	#define STRMSG_S_SCAT_COLNAME_0015 "UID"
//	#define STRMSG_S_SCAT_COLNAME_0016 "Личный номер"
//	#define STRMSG_S_SCAT_COLNAME_0017 "Имя"
//	#define STRMSG_S_SCAT_COLNAME_0018 "Номер предмета"
//	#define STRMSG_S_SCAT_COLNAME_0019 "Префикс"
//	#define STRMSG_S_SCAT_COLNAME_0020 "Суффикс"
	#define STRMSG_S_SCAT_COLNAME_0021 "Экипирован"
//	#define STRMSG_S_SCAT_COLNAME_0022 "Количество"
//	#define STRMSG_S_SCAT_COLNAME_0023 "Время действия"
//	#define STRMSG_S_SCAT_COLNAME_0024 "Время создания"
	#define STRMSG_S_SCAT_COLNAME_0025 "Не экипирован"
//	#define STRMSG_S_SCAT_COLNAME_0026 "Склад"
//	#define STRMSG_S_SCAT_COLNAME_0027 "Аукцион"
//	#define STRMSG_S_SCAT_COLNAME_0028 "Карта"
//	#define STRMSG_S_SCAT_COLNAME_0029 "Координаты"
//	#define STRMSG_S_SCAT_COLNAME_0030 "Пол"
//	#define STRMSG_S_SCAT_COLNAME_0031 "Раса"
//	#define STRMSG_S_SCAT_COLNAME_0032 "Должность"
//	#define STRMSG_S_SCAT_COLNAME_0033 "Тип корабля"
//	#define STRMSG_S_SCAT_COLNAME_0034 "Уровень"
//	#define STRMSG_S_SCAT_COLNAME_0035 "Максимальный уровень"
//	#define STRMSG_S_SCAT_COLNAME_0036 "Опыт"
//	#define STRMSG_S_SCAT_COLNAME_0037 "Потерянные очки опыта"
//	#define STRMSG_S_SCAT_COLNAME_0038 "Тип автораспределения параметров"
//	#define STRMSG_S_SCAT_COLNAME_0039 "Атака"
//	#define STRMSG_S_SCAT_COLNAME_0040 "Защита"
//	#define STRMSG_S_SCAT_COLNAME_0041 "Топливо"
//	#define STRMSG_S_SCAT_COLNAME_0042 "Дух"
//	#define STRMSG_S_SCAT_COLNAME_0043 "Щит"
//	#define STRMSG_S_SCAT_COLNAME_0044 "Ловкость"
//	#define STRMSG_S_SCAT_COLNAME_0045 "Принадлежность"
//	#define STRMSG_S_SCAT_COLNAME_0046 "Слава"
//	#define STRMSG_S_SCAT_COLNAME_0047 "социальное положение"
//	#define STRMSG_S_SCAT_COLNAME_0048 "Общее время соединения"
//	#define STRMSG_S_SCAT_COLNAME_0049 "Время создания"
//	#define STRMSG_S_SCAT_COLNAME_0050 "Последний лог"
//	#define STRMSG_S_SCAT_COLNAME_0051 "Тип"
//	#define STRMSG_S_SCAT_COLNAME_0052 "Всего"
	#define STRMSG_S_SCAT_COLNAME_0053 "Авто(1-1type)"
	#define STRMSG_S_SCAT_COLNAME_0054 "Вулкан(1-1type)"	
	#define STRMSG_S_SCAT_COLNAME_0055 "Дуалист(1-1type)" // 2005-08-01 by hblee : Grenade -> changed to dualist.
	#define STRMSG_S_SCAT_COLNAME_0056 "Пушка(1-1type)"
	#define STRMSG_S_SCAT_COLNAME_0057 "Нарезное(1-2type)"
	#define STRMSG_S_SCAT_COLNAME_0058 "Гатлинг(1-2type)"
	#define STRMSG_S_SCAT_COLNAME_0059 "Пусковая установка(1-2type)"
	#define STRMSG_S_SCAT_COLNAME_0060 "Автоматическое(1-2type)"
	#define STRMSG_S_SCAT_COLNAME_0061 "Ракета(2-1type)"
	#define STRMSG_S_SCAT_COLNAME_0062 "Реактивный снаряд(2-1type)"
	#define STRMSG_S_SCAT_COLNAME_0063 "Кассетное(2-1type)"
	#define STRMSG_S_SCAT_COLNAME_0064 "Мина(2-1type)"
	#define STRMSG_S_SCAT_COLNAME_0065 "Щит(2-2type)"
	#define STRMSG_S_SCAT_COLNAME_0066 "учебное(2-2type)"
	#define STRMSG_S_SCAT_COLNAME_0067 "Протонное(2-2type)"
	#define STRMSG_S_SCAT_COLNAME_0068 "Ловушка(2-2type)"
	#define STRMSG_S_SCAT_COLNAME_0069 "Защита"
	#define STRMSG_S_SCAT_COLNAME_0070 "Поддержка"
	#define STRMSG_S_SCAT_COLNAME_0071 "Энергия"
	#define STRMSG_S_SCAT_COLNAME_0072 "Металл"
	#define STRMSG_S_SCAT_COLNAME_0073 "Карточка"
	#define STRMSG_S_SCAT_COLNAME_0074 "Улучшение"
	#define STRMSG_S_SCAT_COLNAME_0075 "Танк"
	#define STRMSG_S_SCAT_COLNAME_0076 "Пули"
	#define STRMSG_S_SCAT_COLNAME_0077 "Квест"
	#define STRMSG_S_SCAT_COLNAME_0078 "Радар"
	#define STRMSG_S_SCAT_COLNAME_0079 "Компьютер"
	#define STRMSG_S_SCAT_COLNAME_0080 "Усиление"
	#define STRMSG_S_SCAT_COLNAME_0081 "Предотвращение разрушения"		// 2005-08-02 by cmkwon
	#define STRMSG_S_SCAT_COLNAME_0082 "Бластер"				// 2005-08-02 by cmkwon
	#define STRMSG_S_SCAT_COLNAME_0083 "Рельсовое"				// 2005-08-02 by cmkwon
//	#define STRMSG_S_SCAT_COLNAME_0081 "Все типы"
//	#define STRMSG_S_SCAT_COLNAME_0082 "Весь сервер"
//	#define STRMSG_S_SCAT_COLNAME_0083 "Имя сервера"
//	#define STRMSG_S_SCAT_COLNAME_0084 "Тип сервера"
//	#define STRMSG_S_SCAT_COLNAME_0085 "IP Сервера, порт"
//	#define STRMSG_S_SCAT_COLNAME_0086 "Текущее кол-во пользователей"
//	#define STRMSG_S_SCAT_COLNAME_0087 "Состояние сервера"
//	#define STRMSG_S_SCAT_COLNAME_0088 "Группа серверов"
//	#define STRMSG_S_SCAT_COLNAME_0089 "Field server"
//	#define STRMSG_S_SCAT_COLNAME_0090 "Неизвестно"
//	#define STRMSG_S_SCAT_COLNAME_0091 "Недоступен"
//	#define STRMSG_S_SCAT_COLNAME_0092 "Нормальный"
//	#define STRMSG_S_SCAT_COLNAME_0093 "Ненормальный"
	#define STRMSG_S_SCAT_COLNAME_0094 "Администратор"

	#define STRMSG_S_SCADMINTOOL_050512_0000	"CAST(l.CurrentCount AS VARCHAR(10)) + 'единиц, Param1:' + CAST(l.Param1 AS VARCHAR(10))"
// 3_end
///////////////////////////////////////////////////////////////////////////////
	
	
///////////////////////////////////////////////////////////////////////////////
// 4
	// 4-1 AtumMonitor - STRMSG
//	#define STRMSG_S_SCMONITOR_0000 "Список команд\r\n"
//	#define STRMSG_S_SCMONITOR_0001 "----- Список запасных аккаунтов ---------------------------------------\r\n"
//	#define STRMSG_S_SCMONITOR_0002 "  Аккаунт: \'%s\', Настоящий пароль: \'%s\', Временный пароль: \'%s\'\r\n"
//	#define STRMSG_S_SCMONITOR_0003 "  Аккаунт: \'%s\' \r\n"
//	#define STRMSG_S_SCMONITOR_0004 "Укажите директорию с обновлениями."
//	#define STRMSG_S_SCMONITOR_0005 "\r\nСоздание архива из %s в %s...\r\n"
//	#define STRMSG_S_SCMONITOR_0006 "Переименовать группу серверов"
//	#define STRMSG_S_SCMONITOR_0007 "Файл успешно создан.\r\n\r\nDB информация: %s(%d), %s"
//	#define STRMSG_S_SCMONITOR_0008 "%04d(%2d -  активен) %3d/%3d"
//	#define STRMSG_S_SCMONITOR_0009 "%04d(%2d -неактивен) %3d/%3d"
//	#define STRMSG_S_SCMONITOR_0010 "Данные с сервера успешно загружены"
//	#define STRMSG_S_SCMONITOR_0011 "Успешно отображено состояние услуг"
//	#define STRMSG_S_SCMONITOR_0012 "%04d(%2d -  активен)"
//	#define STRMSG_S_SCMONITOR_0013 "%04d(%2d -неактивен)"
//	#define STRMSG_S_SCMONITOR_0014 "Обновление Списка Информации Версии ГОТОВО!"
//	#define STRMSG_S_SCMONITOR_0015 "Обновление Списка Заблокированных Аккаунтов ГОТОВО!"
//	#define STRMSG_S_SCMONITOR_0016 "Обслуживание свободного сервера временно приостановлено."
//	#define STRMSG_S_SCMONITOR_0017 "Свободный сервер запущен."
//	#define STRMSG_S_SCMONITOR_0018 "Полевой сервер недоступен."
//	#define STRMSG_S_SCMONITOR_0019 "Вы действительно хотите закрыть полевой сервер?"
//	#define STRMSG_S_SCMONITOR_0020 "Информация о списке обновлений (Максимум 1492 Байтов)\r\n\r\n    Список версий[%3d], Соответствие данных[%4dBytes]"
//	#define STRMSG_S_SCMONITOR_0021 "Вы действительно хотите закрыть сервер Pre?"
//	#define STRMSG_S_SCMONITOR_0022 "Вы действительно хотите закрыть сервер IM?"
//	#define STRMSG_S_SCMONITOR_0023 "Вы действительно хотите закрыть сервер NPC?"
//	#define STRMSG_S_SCMONITOR_0024 "%Yгод %mмесяц %dдень %Hчас %Mминута %Sсекунда"
//	#define STRMSG_S_SCMONITOR_0025 "нет события(%d)"
//	#define STRMSG_S_SCMONITOR_0026 "Открыть событие участий в бете(%d)"
//	#define STRMSG_S_SCMONITOR_0027 "Не знать событий(%d)"
//	#define STRMSG_S_SCMONITOR_0028 "Установить время для следующей битвы по захвату"
//	#define STRMSG_S_SCMONITOR_0029 "Стандартное время для следующей битвы по захвату"
//	#define STRMSG_S_SCMONITOR_0030 "Бригада захвата"

	// 4-2 AtumMonitor - STRERR
//	#define STRERR_S_SCMONITOR_0000 "  ==> Успешная команда.\r\n"
//	#define STRERR_S_SCMONITOR_0001 "  ==> Команда не успешна.\r\n"
//	#define STRERR_S_SCMONITOR_0002 "Невозможно соединение с базой данных."
//	#define STRERR_S_SCMONITOR_0003 "Версии не существует"
//	#define STRERR_S_SCMONITOR_0004 "Введите имя папки, которую хотите запаковать"
//	#define STRERR_S_SCMONITOR_0005 "Введите имя папки, которую хотите распаковать"
//	#define STRERR_S_SCMONITOR_0006 "Введите начальную версию"
//	#define STRERR_S_SCMONITOR_0007 "Введите финальную версию"
//	#define STRERR_S_SCMONITOR_0008 "Выберите путь, куда распаковать zip архив с обновлением"
//	#define STRERR_S_SCMONITOR_0009 "Файл не соединяется"
//	#define STRERR_S_SCMONITOR_0010 "Выберите сервер!"
//	#define STRERR_S_SCMONITOR_0011 "Невозможно соединиться с базой данных"
//	#define STRERR_S_SCMONITOR_0012 "[ОШИБКА]невозможно создать тип сообщения: %s(%#04x) in CLeftView::OnSocketNotify()\n"
//	#define STRERR_S_SCMONITOR_0013 "Слишком много информации по обновлению.(Номер версии[%3d], совместимость данных[%4dBytes])\r\n\r\n    Нужно упорядочить список версий."
//	#define STRERR_S_SCMONITOR_0014 "Удаленная функция.\r\nИспользуйте инструмент настройки."
//	#define STRERR_S_SCMONITOR_0015 "Это не карта города"
//	#define STRERR_S_SCMONITOR_0016 "Вы не можете создать кнопку EDIT."
//	#define STRERR_S_SCMONITOR_0017 "Вы зарегистрировали уже имеющийся файл."

// 4_end	
///////////////////////////////////////////////////////////////////////////////
	

///////////////////////////////////////////////////////////////////////////////
// 5 - FieldServer
	// 5-1 Field<->Log
	#define STRMSG_S_F2LOGCONNECT_0000 "[Ошибка] WndProc(), Невозможно установить соединение с LogServer[%15s:%4d] Попытка повторного соединения.\r\n"
	#define STRMSG_S_F2LOGCONNECT_0001 "Подключение к Log Server завершено.\n"
	#define STRMSG_S_F2LOGCONNECT_0002 "Соединение с Log Server[%15s:%4d] утеряно. Попытка повторного соединения.\r\n"

	// 5-2 Field<->Pre
	#define STRMSG_S_F2PRECONNECT_0000 "[Ошибка] WndProc(),Невозможно установить соединение с PreServer[%15s:%4d] Попытка повторного соединения.\r\n"
	#define STRMSG_S_F2PRECONNECT_0001 "Подключение к Pre Server завершено.\n"
	#define STRMSG_S_F2PRECONNECT_0002 "T_ERROR %s(%#04X) получена от %s[%s]\r\n"
	#define STRMSG_S_F2PRECONNECT_0003 "Неизвестная Error@WM_PRE_PACKET_NOTIFY: %s(%#04x)\n"
	#define STRMSG_S_F2PRECONNECT_0004 "Соединение с Pre Server[%15s:%4d] утеряно. Попытка повторного соединения.\r\n"

	// 5-3 Field<->IM
	#define STRMSG_S_F2IMCONNECT_0000 "[Ошибка] WndProc(),Невозможно установить соединение с IMServer[%15s:%4d] Попытка повторного соединения.\r\n"
	#define STRMSG_S_F2IMCONNECT_0001 "Подключение к IM Server завершено.\n"
	#define STRMSG_S_F2IMCONNECT_0002 "Соединение с IM Server[%15s:%4d] утеряно. Попытка повторного соединения.\r\n"
	#define STRMSG_S_F2IMCONNECT_0003 "T_ERROR %s(%#04X) получена от %s[%s]\r\n"
	#define STRMSG_S_F2IMCONNECT_0004 "Неизвестная Error@WM_IM_PACKET_NOTIFY: %s(%#04x)\n"

	// 5-3 Field - DB
	#define STRMSG_S_F2DBQUERY_0000 "Несуществующий запрос к базе данных Field Server! %d\n"
	#define STRMSG_S_F2DBQUERY_0001 "Данный предмет не существует."
	#define STRMSG_S_F2DBQUERY_0002 "'%s' подал заявку. Обещанный предмет"
	#define STRMSG_S_F2DBQUERY_0003 "выдан. Нажмите, F5 чтобы проверить инвентарь."
	#define STRMSG_S_F2DBQUERY_0004 "Навык %s(%d)добавлен"
	#define STRMSG_S_F2DBQUERY_0005 "Данный предмет не существует."
	#define STRMSG_S_F2DBQUERY_0006 "Не удалось получить предмет."

	// 5-4 Field - CityWar
	#define STRMSG_S_F2CITYWAR_0000 "Начало битвы за контроль над городом: %d(%10s) occGuildName(%s)\r\n"
	#define STRMSG_S_F2CITYWAR_0001 "Участвует бригада: GuildUID(%4d) GuildName(%10s) GuildMaster(%d)\r\n"
	#define STRMSG_S_F2CITYWAR_0002 "Битва с монстрами за контроль над городом: %d(%10s) occGuildName(%s)\r\n"
	#define STRMSG_S_F2CITYWAR_0003 "Общий урон ==> GuildName(%10s) SumOfDamage(%8.2f)\r\n"
	#define STRMSG_S_F2CITYWAR_0004 "Битва за контроль над городом: %d(%10s) CityMapIndex(%d) QuestIndex(%d) OccGuildID(%d) OccGuildName(%s) OccGuildMasterUID(%d) Время Битвы(%s)\r\n"
	#define STRMSG_S_F2CITYWAR_0005 "[Ошибка] SetCityWarState_ DBError, MapIndex(%d)\r\n"
	#define STRMSG_S_F2CITYWAR_0006 "Через %dмин., \"%s\" начнется битва за контроль над городом."
	#define STRMSG_S_F2CITYWAR_0007 "Через %dмин., \"%s\" завершится битва за контроль над городом."
	#define STRMSG_S_F2CITYWAR_0008 "Вызван монстр для битвы за контроль над городом(%s) : Под контролем NPC"
	#define STRMSG_S_F2CITYWAR_0009 "Вызван монстр для битвы за контроль над городом(%s) : Под контролем бригады %s "
	#define STRMSG_S_F2CITYWAR_0010 "\"NPC\"на данный момент контролируют \"%s\"."
	#define STRMSG_S_F2CITYWAR_0011 "Бригада \"%s\" на данный момент захватила \"%s\"."

	// 5-4 Field - Quest
	#define STRMSG_S_F2QUEST_0000 "Не удалость загрузить задание"
	#define STRMSG_S_F2QUEST_0001 "задание не было загружено.\r\n"
//	#define STRMSG_S_F2QUEST_0002 "Задание \'%30s\' Номер %d -> OK\r\n"

	// 5-4 Field - config
	#define STRMSG_S_F2CONFIG_0000 "Сервер помечен как тестовый! \r\n\r\nLoadFieldServerDataDebug() необходимо отключить! "
	#define STRMSG_S_F2NOTIFY_0000 "экран загрузки %d: %d до %5.2f(%2.1f%%)"
	#define STRMSG_S_F2NOTIFY_0001 "экран загрузки монстров %d: %s до %5.2f"
	#define STRMSG_S_F2NOTIFY_0002 "1й тип"
	#define STRMSG_S_F2NOTIFY_0003 "2й тип"
	#define STRMSG_S_F2NOTIFY_0004 "Мон1(%s)"
	#define STRMSG_S_F2NOTIFY_0005 "Мон2(%s)"
	#define STRMSG_S_F2NOTIFY_0006 "Неверный тип оружия! Обратитесь к администратору!"
	#define STRMSG_S_F2NOTIFY_0007 "1-1тип: %4.1f vs %4.1f -> точность уменьшена на %2.2f%% "
	#define STRMSG_S_F2NOTIFY_0008 "%s->%s промах, точность(%d>%5.2f)"
	#define STRMSG_S_F2NOTIFY_0009 "%s->%s промах, точность(%d>%5.2f) -%5.2f"
	#define STRMSG_S_F2NOTIFY_0010 "%s->%s промах, точность(%d>%5.2f)"
	#define STRMSG_S_F2NOTIFY_0011 "1-2тип: %4.1f против %4.1f -> Урон уменьшен на %2.2f%%(%4.1f->%4.1f)"
	#define STRMSG_S_F2NOTIFY_0012 "%s->%s, наносит %5.2f(%5.2f-%d/255) (%d<=%5.2f)"
	#define STRMSG_S_F2NOTIFY_0013 "%s->%s, получает %5.2f(%5.2f-%d/255) (%d<=%5.2f)"
	#define STRMSG_S_F2NOTIFY_0014 "%s->%s(%d, HP:%5.2f), наносит %5.2f(%5.2f-%d/255) (%d<=%5.2f)"
	#define STRMSG_S_F2NOTIFY_0015 "%s->%s, получает %5.2f(%5.2f-%d/255) (%d<=%5.2f)"
	#define STRMSG_S_F2NOTIFY_0016 "Промах: точность упала > %d"
	#define STRMSG_S_F2NOTIFY_0017 "Осталось: [%#08x]: %5.2f(%5.2f-%5.2f)"
	#define STRMSG_S_F2NOTIFY_0018 "Информации о патронах не существует. Обратитесь к администратору."
	#define STRMSG_S_F2NOTIFY_0019 "Информации о калибре патронов не существует. %s %d"
	#define STRMSG_S_F2NOTIFY_0020 "Информация о патронах. %s %d"
	#define STRMSG_S_F2NOTIFY_0021 "Во время ивента гиперпрыжок невозможен."
	#define STRMSG_S_F2NOTIFY_0022 "Во время смерти гиперпрыжок невозможен."
	#define STRMSG_S_F2NOTIFY_0023 "Во время битвы между звеньями гиперпрыжок невозможен."
	#define STRMSG_S_F2NOTIFY_0024 "Ошибка загрузки карты! Обратитесь к администратору!"
	#define STRMSG_S_F2NOTIFY_0025 "Ошибка загрузки карты! Обратитесь к администратору! Координаты гиперпрыжка %d, %d неверны!\r\n"
	#define STRMSG_S_F2NOTIFY_0026 "Во время битвы между звеньями гиперпрыжок невозможен."
	#define STRMSG_S_F2NOTIFY_0027 "Гиперпрыжок(%04d) невозможен: Process_FC_CHARACTER_DEAD_GAMESTART(), %s\r\n"
	#define STRMSG_S_F2NOTIFY_0028 "1 -> Персонаж %10s ,получает урон %5.2f"
	#define STRMSG_S_F2NOTIFY_0029 "1 -> Персонаж %10s ,наносит урон %5.2f"
	#define STRMSG_S_F2NOTIFY_0030 "1 -> Персонаж %10s ,наносит урон %5.2f"
	#define STRMSG_S_F2NOTIFY_0031 "1 -> Персонажr %10s ,наносит урон %5.2f"
	#define STRMSG_S_F2NOTIFY_0032 "2 -> Персонаж %10s ,получает урон %5.2f"
	#define STRMSG_S_F2NOTIFY_0033 "2 -> Персонаж %10s ,наносит урон %5.2f"
	#define STRMSG_S_F2NOTIFY_0034 "2 -> Монстр %3d ,наносит урон %5.2f(%d)"
	#define STRMSG_S_F2NOTIFY_0035 "2 -> Персонаж %10s ,наносит урон %5.2f"
	#define STRMSG_S_F2NOTIFY_0036 "2 -> Персонаж %10s ,наносит урон %5.2f"
	#define STRMSG_S_F2NOTIFY_0037 "2 -> Монстр %3d ,получает урон %5.2f"
	#define STRMSG_S_F2NOTIFY_0038 "MINE -> Персонаж %10s , наносит урон %5.2f"
	#define STRMSG_S_F2NOTIFY_0039 "MINE -> Персонаж %10s ,наносит урон %5.2f"
	#define STRMSG_S_F2NOTIFY_0040 "MINE -> Монстр %10s ,наносит урон %5.2f"
	#define STRMSG_S_F2NOTIFY_0041 "Инициализация параметров прошла успешно"
	#define STRMSG_S_F2NOTIFY_0042 "Невозможно использовать, когда персонаж мертв."
	#define STRMSG_S_F2NOTIFY_0043 "ENCHANT_INFO не существует"
	#define STRMSG_S_F2NOTIFY_0044 "Улучшение успешно"
	#define STRMSG_S_F2NOTIFY_0045 "Улучшение не удалось"
	#define STRMSG_S_F2NOTIFY_0046 "Не принадлежит бригаде"
	#define STRMSG_S_F2NOTIFY_0047 "Уже в режиме ожидания"
	#define STRMSG_S_F2NOTIFY_0048 "Пожалуйста, попробуйте позднее."
	#define STRMSG_S_F2NOTIFY_0049 "Вы или кто-то другой является командиром бригады"
	#define STRMSG_S_F2NOTIFY_0050 "Уже в битве бригад"
	#define STRMSG_S_F2NOTIFY_0051 "Не оба командира бригад находятся на одной карте."
	#define STRMSG_S_F2NOTIFY_0052 "Не все члены звена находятся на одной карте."
	#define STRMSG_S_F2NOTIFY_0053 "Не все члены звена находятся на одной карте."
	#define STRMSG_S_F2NOTIFY_0054 "Вы не состоите в бригаде"
	#define STRMSG_S_F2NOTIFY_0055 "Ошибка присоединения к бригаде"
	#define STRMSG_S_F2NOTIFY_0056 "Ни вы, ни другой персонаж не являетесь командирами бригады."
	#define STRMSG_S_F2NOTIFY_0057 "Не оба командира бригад находятся на одной карте."
	#define STRMSG_S_F2NOTIFY_0058 "Вы не состоите в бригаде"
	#define STRMSG_S_F2NOTIFY_0059 "Получатель не соответствует"
	#define STRMSG_S_F2NOTIFY_0060 "Ни вы, ни другой персонаж не являетесь командирами бригады."
	#define STRMSG_S_F2NOTIFY_0061 "Успешная защита города!"
	#define STRMSG_S_F2NOTIFY_0062 "Ошибка миссии. Пожалуйста, сообщите администратору."
	#define STRMSG_S_F2NOTIFY_0063 "Данный предмет (%s) не подходит для этой локации."
	#define STRMSG_S_F2NOTIFY_0064 "Двигатель нельзя убрать"
	#define STRMSG_S_F2NOTIFY_0065 "Переместить предмет: (%I64d, %d) -> (%I64d, %d)"
	#define STRMSG_S_F2NOTIFY_0066 "Неправильное перемещение предмета: (%I64d, %d) -> (%I64d, %d)"
	#define STRMSG_S_F2NOTIFY_0067 "ИВЕНТ(%d) ошибка в Process_FC_EVENT_REQUEST_WARP(), %s\r\n"
	#define STRMSG_S_F2NOTIFY_0068 "Информация об ивенте на карте некорректна! Сообщите администратору!"
	#define STRMSG_S_F2NOTIFY_0069 "Указанная цель гиперпрыжка не существует"
	#define STRMSG_S_F2NOTIFY_0070 "Ошибка приобретения предмета. Пожалуйста, обратитесь к администратору."
	#define STRMSG_S_F2NOTIFY_0071 "Уровень умения, которое вы хотите приобрести, ниже вашего или равен ему."
	#define STRMSG_S_F2NOTIFY_0072 "Ошибка предмета. Необходимо умение."
	#define STRMSG_S_F2NOTIFY_0073 "Ошибка продажи предмета. Сообщите администратору."
	#define STRMSG_S_F2NOTIFY_0074 "Ошибка покупки предмета. Сообщите администратору."
	#define STRMSG_S_F2NOTIFY_0075 "\'4Game предмет \'куплен."
	#define STRMSG_S_F2NOTIFY_0076 "список товаров : \'%s(%dед.)\'"
	#define STRMSG_S_F2NOTIFY_0077 "Уже присоединился к звену."
	#define STRMSG_S_F2NOTIFY_0078 "Невозможно присоединиться, если вы – командир звена."
	#define STRMSG_S_F2NOTIFY_0079 "Невозможно присоединиться во время битвы между звеньями"
	#define STRMSG_S_F2NOTIFY_0080 "Просмотр всей информации о членах звена не предусмотрен!"
	#define STRMSG_S_F2NOTIFY_0081 "Неверная информация об ивенте карты! Сообщите администратору!!!"
	#define STRMSG_S_F2NOTIFY_0082 "С данным аккаунтом транзакции недопустимы."
	#define STRMSG_S_F2NOTIFY_0083 "%s – превышение загрузки."
	#define STRMSG_S_F2NOTIFY_0084 "Возможные координаты передвижения: (5, 5) -> (%d, %d)"
	#define STRMSG_S_F2NOTIFY_0085 "Пользователь: "
	#define STRMSG_S_F2NOTIFY_0086 "Можно увидеть максимум 20 человек."
	#define STRMSG_S_F2NOTIFY_0087 "Данный пользователь (%s) не существует"
	#define STRMSG_S_F2NOTIFY_0088 "Не принадлежит звену"
	#define STRMSG_S_F2NOTIFY_0089 "Текущее время: %d:%d, время Артум: %d:%d"
	#define STRMSG_S_F2NOTIFY_0090 "Новое время: %d:%d, время Артум: %d:%d"
	#define STRMSG_S_F2NOTIFY_0091 "Нет соединения с NPC server"
	#define STRMSG_S_F2NOTIFY_0092 "Данный предмет (%d) не существует!"
	#define STRMSG_S_F2NOTIFY_0093 "Лимит – 10 ед., если предмет не является складывающимся"
	#define STRMSG_S_F2NOTIFY_0094 "Карта \'%s\' 's всего присоединилось: %d чел."
	#define STRMSG_S_F2NOTIFY_0095 "Карта %s %s одновременно подключено: %d чел. - '%s'(*)"
	#define STRMSG_S_F2NOTIFY_0096 "Карта %s %s одновременно подключено: %d чел. - '%s'"
	#define STRMSG_S_F2NOTIFY_0097 "Текущий канал карты: %s, %d(%d)"
	#define STRMSG_S_F2NOTIFY_0098 "Информации о патронах не существует. Сообщите администратору."
	#define STRMSG_S_F2NOTIFY_0099 "Информации о калибре патронов не существует. %s %d"
	#define STRMSG_S_F2NOTIFY_0100 "Информации о патронах не существует. Сообщите администратору."
	#define STRMSG_S_F2NOTIFY_0101 "Информации о калибре патронов не существует. %s %d"
	#define STRMSG_S_F2NOTIFY_0102 "Пользователь(%s)не существует"
	#define STRMSG_S_F2NOTIFY_0103 "Пользователь(%s)мертв"
	#define STRMSG_S_F2NOTIFY_0104 "Пользователь(%s)не существует!"
	#define STRMSG_S_F2NOTIFY_0105 "Сделать Стандартным Аккаунтом"
	#define STRMSG_S_F2NOTIFY_0106 "Стандартный Аккаунт отменен"
	#define STRMSG_S_F2NOTIFY_0107 "Неуязвимость включена"
	#define STRMSG_S_F2NOTIFY_0108 "Неуязвимость выключена"
	#define STRMSG_S_F2NOTIFY_0109 "Урон оружия изменится на %5.0f%% "
	#define STRMSG_S_F2NOTIFY_0110 "Отмена при повторной установке предмета"
	#define STRMSG_S_F2NOTIFY_0111 "Отмена при повторной установке предмета"
	#define STRMSG_S_F2NOTIFY_0112 "Данный пользователь(%s)не существует"
	#define STRMSG_S_F2NOTIFY_0113 "Невидимость выключена"
	#define STRMSG_S_F2NOTIFY_0114 "Невидимость включена"
	#define STRMSG_S_F2NOTIFY_0115 "Ивент %s не идет"
	#define STRMSG_S_F2NOTIFY_0116 "Начался ивент %s (увеличение:%4.2f, время ивента: %3dмин.)"
	#define STRMSG_S_F2NOTIFY_0117 "Сделать стандартным премиум Аккаунтом"
	#define STRMSG_S_F2NOTIFY_0118 "Не удалось сделать премиум Аккаунтом"
	#define STRMSG_S_F2NOTIFY_0119 "Сделать супер премиум Аккаунтом"
	#define STRMSG_S_F2NOTIFY_0120 "Это не карта для битвы за контроль над городом"
	#define STRMSG_S_F2NOTIFY_0121 "Невозможно начать битву за контроль над городом"
	#define STRMSG_S_F2NOTIFY_0122 "Невозможно завершить битву за контроль над городом"
	#define STRMSG_S_F2NOTIFY_0123 "Стелс-режим отключён"
	#define STRMSG_S_F2NOTIFY_0124 "Стелс-режим активирован"
	#define STRMSG_S_F2NOTIFY_0125 "Карта недоступна"
	#define STRMSG_S_F2NOTIFY_0126 "Установлен ивент \\aСчастливый час\\a [время:%4dмин.)]"
	#define STRMSG_S_F2NOTIFY_0127 "Ивент \\aСчастливый час\\a завершен"
	#define STRMSG_S_F2NOTIFY_0128 "1 -> Монстр %3d, нанес урон %5.2f"
	#define STRMSG_S_F2NOTIFY_0129 "1type -> Монстр %3d, нанес урон %5.2f"
	#define STRMSG_S_F2NOTIFY_0130 "Совершен вход с полномочиями %s"
	#define STRMSG_S_F2NOTIFY_0131 "Не прервыайте завершение процедуры %s: CS(%d), DBStore(%d)\r\n"
	#define STRMSG_S_F2NOTIFY_0132 "ОШИБКА@CharacterGameEndRoutine(): Не удалось уничтожить личный состав звена! %s\r\n"
// 2005-11-24 by cmkwon, 
//	#define STRMSG_S_F2NOTIFY_0133 "Префикс \'%s\' јє°ш: %d <= %d <= %d\r\n"
//	#define STRMSG_S_F2NOTIFY_0134 "Суффикс \'%s\' јє°ш: %d <= %d <= %d\r\n"
	#define STRMSG_S_F2NOTIFY_0135 "%s: Остановлен!"
	#define STRMSG_S_F2NOTIFY_0136 "КРИТИЧЕСКАЯ ОШИБКА: Сообщите администратору! Ошибка назначения переменных продажи!"
	#define STRMSG_S_F2NOTIFY_0137 "Предмет %s был удален."
	#define STRMSG_S_F2NOTIFY_0138 "Канал, на котором вы находитесь, в данный момент отключен, поэтому монстры и прочие функции недоступны"
	#define STRMSG_S_F2NOTIFY_0139 "Остановлен. Воспользуйтесь другим каналом."
	#define STRMSG_S_F2NOTIFY_0140 "Объект гиперпрыжка.[%s,%2dед.]: %04d[%1s%4d]"
	#define STRMSG_S_F2NOTIFY_0141 "Изменение таймера %s\r\n"
	#define STRMSG_S_F2NOTIFY_0142 "Автовосстановление HP остановлено"
	#define STRMSG_S_F2NOTIFY_0143 "Автовосстановление HP остановлено, т.к. это недопустимая для посадки зона."
	#define STRMSG_S_F2NOTIFY_0144 "HP 5.2f экстренное восстановление."
	#define STRMSG_S_F2NOTIFY_0145 "Постепенный рост HP остановлен(осталось: %d)"
	#define STRMSG_S_F2NOTIFY_0146 "Постепенный рост DP остановлен(осталось: %d)"
	#define STRMSG_S_F2NOTIFY_0147 "Постепенный рост EP остановлен(осталось: %d)"
	#define STRMSG_S_F2NOTIFY_0148 "%s - ивент завершен."
	#define STRMSG_S_F2NOTIFY_0149 "%s - ивент проходит (увеличение %4.2f, осталось:%3dмин.)"
	#define STRMSG_S_F2NOTIFY_0150 "Команда не была выполнена."
	#define STRMSG_S_F2NOTIFY_0151 "\\cYour last connection was at: \\c\\y%s\\y"
	#define STRMSG_S_F2NOTIFY_0152 "\\cYour gear was created on the: \\c\\y%s\\y"
	#define STRMSG_S_F2NOTIFY_0153 "\\cYou played \\y%u Day(s) %u Hour(s) %u Minute(s)\\y and \\y%u Seconds(s)\\y until now!\\c"


	// 5-5 Field - NOTIFY Error
	#define STRERR_S_F2NOTIFY_0000 "Ошибка распределения очков опыта(%s, %s(%d)): fОбщий урон(%d) < 0.0f или пустой вектор: %d, дистанция(%5.1f)\n"
	#define STRERR_S_F2NOTIFY_0001 "Сообщение об ошибке при начале игры ClientState[%d]\r\n"
	#define STRERR_S_F2NOTIFY_0002 "Сообщение об ошибке при начале игры ClientState[%d]\r\n"
	#define STRERR_S_F2NOTIFY_0003 "ГИПЕРПРЫЖОК(%04d) невозможно обращение к ProcessQuestResult(), %s\r\n"
	#define STRERR_S_F2NOTIFY_0004 "Неверная информация об ивенте карты! Сообщите администратору! Положение(%s, %s, %04d), Цель(%04d, %d)\r\n"
	#define STRERR_S_F2NOTIFY_0005 "ГИПЕРПРЫЖОК(%d) невозможно обращение к T_FC_PARTY_REQUEST_PARTY_WARP(), %s\r\n"
	#define STRERR_S_F2NOTIFY_0006 "Неверная информация об ивенте карты! Сообщите администратору! Положение(%s, %s, %04d), Цель(%04d, %d)\r\n"
	#define STRERR_S_F2NOTIFY_0007 "ГИПЕРПРЫЖОК невозможно обращение к T_FC_PARTY_REQUEST_PARTY_WARP(). %s\r\n"
	#define STRERR_S_F2NOTIFY_0008 "ИВЕНТ(%d) обращение невозможно(командир звена) в Process_FC_PARTY_REQUEST_PARTY_WARP_WITH_MAP_NAME(). %s\r\n"
	#define STRERR_S_F2NOTIFY_0009 "ГИПЕРПРЫЖОК(%04d) невозможно обращение к Process_FC_PARTY_REQUEST_PARTY_WARP_WITH_MAP_NAME(). %s\r\n"
	#define STRERR_S_F2NOTIFY_0010 "ИВЕНТ(%d) невозможно обращение к Process_FC_EVENT_REQUEST_WARP(), %s\r\n"
	#define STRERR_S_F2NOTIFY_0011 "ГИПЕРПРЫЖОК невозможно обращение к T_FC_PARTY_REQUEST_PARTY_WARP(). %s\r\n"
	#define STRERR_S_F2NOTIFY_0012 "Скачок отряда не удался: %s -> расстояние: %5.2f, bodycon: %d, %d"
	#define STRERR_S_F2NOTIFY_0013 "ГИПЕРПРЫЖОК(%04d) невозможно обращение к Process_FC_CHARACTER_DEAD_GAMESTART(), %s\r\n"
	#define STRERR_S_F2NOTIFY_0014 "%s -> щелчок по дублированной кнопке ОК!!!\r\n"
	#define STRERR_S_F2NOTIFY_0015 "Квест не загружен.\r\n"
	#define STRERR_S_F2NOTIFY_0016 "ГИПЕРПРЫЖОК(%s) невозможно обращение к HandleAdminCommands(), /move, %s\r\n"
	#define STRERR_S_F2NOTIFY_0017 "ГИПЕРПРЫЖОК(%s) невозможно обращение к HandleAdminCommands(), /send, %s\r\n"
	#define STRERR_S_F2NOTIFY_0018 "КРИТИЧЕСКАЯ ОШИБКА: это сообщение должно отсылаться игрокам полевого сервера, к которому они не относятся. проверьте\r\n"
	#define STRERR_S_F2NOTIFY_0019 "ГИПЕРПРЫЖОК(%04d) невозможно обращение к  T_FI_ADMIN_CALL_CHARACTER, %s\r\n"
	#define STRERR_S_F2NOTIFY_0020 "ГИПЕРПРЫЖОК(%s) невозможно обращение к  T_FI_ADMIN_MOVETO_CHARACTER, %s\r\n"

	// 5-6 Field - Event
	#define STRMSG_S_F2EVENTTYPE_0000 "Опыт"
	#define STRMSG_S_F2EVENTTYPE_0001 "SPI"
	#define STRMSG_S_F2EVENTTYPE_0002 "Восстановление опыта"
	#define STRMSG_S_F2EVENTTYPE_0003 "Выпадение предметов"
	#define STRMSG_S_F2EVENTTYPE_0004 "Выпадение редких предметов"
	#define STRMSG_S_F2EVENTTYPE_0005 "Неизвестный ивент"
// 5_end	
///////////////////////////////////////////////////////////////////////////////
	

///////////////////////////////////////////////////////////////////////////////
// 6 - IMServer
	// 6-1 IM<->Pre
	#define STRMSG_S_I2PRECONNECT_0000 "Выполнен вход на Pre Server.\n"
	#define STRMSG_S_I2PRECONNECT_0001 "Соединение с Pre Server[%15s:%4d]потеряно. Повторное соединение.\r\n"

	// 6-2 IM Notify
	#define STRMSG_S_I2NOTIFY_0000 "\'%s\' уже существует."
	#define STRMSG_S_I2NOTIFY_0001 "\'%s\' уже в бригаде."
	#define STRMSG_S_I2NOTIFY_0002 "\'%s\' имя уже занято другой бригадой."
	#define STRMSG_S_I2NOTIFY_0003 "Ошибка загрузки бригады - Сообщите администратору!"
	#define STRMSG_S_I2NOTIFY_0004 "Ваш друг '%s' вошел в игру"
	#define STRMSG_S_I2NOTIFY_0005 "Проверка предыдущего звена"
	#define STRMSG_S_I2NOTIFY_0006 "Предыдущего звена не существует"
	#define STRMSG_S_I2NOTIFY_0007 "Снова присоединился к звену"
	#define STRMSG_S_I2NOTIFY_0008 "У вас уже есть звено, к которому вы присоединились."
	#define STRMSG_S_I2NOTIFY_0009 "Критическая ошибка: Критическая ошибка звена! в T_IC_PARTY_GET_MEMBER"
	#define STRMSG_S_I2NOTIFY_0010 "Неверное состояние состава звена"
	#define STRMSG_S_I2NOTIFY_0011 "Члены звена уже вступили в бригаду"
	#define STRMSG_S_I2NOTIFY_0012 "Уже вступил в бригаду"
	#define STRMSG_S_I2NOTIFY_0013 "Вы не можете пригласить самого себя"
	#define STRMSG_S_I2NOTIFY_0014 "Вы находитесь в состоянии, когда невозможно вступить в бригаду."
	#define STRMSG_S_I2NOTIFY_0015 "Вы исчерпали лимит членов бригады, которые могут присоединиться."
	#define STRMSG_S_I2NOTIFY_0016 "Вы находитесь в состоянии, когда невозможно вступить в бригаду."
	#define STRMSG_S_I2NOTIFY_0017 "Командир отряда не может покинуть бригаду"
	#define STRMSG_S_I2NOTIFY_0018 "Нельзя покинуть бригаду во время битвы между бригадами"
	#define STRMSG_S_I2NOTIFY_0019 "Нельзя исключать из бригады во время битвы между бригадами"
	#define STRMSG_S_I2NOTIFY_0020 "Командира бригады нельзя исключить"
	#define STRMSG_S_I2NOTIFY_0021 "Во время битвы между бригадами нельзя расформировать бригаду"
	#define STRMSG_S_I2NOTIFY_0022 "Нельзя изменить имя на такое же"
	#define STRMSG_S_I2NOTIFY_0023 "Сейчас нельзя изменять название бригады"
	#define STRMSG_S_I2NOTIFY_0024 "Сейчас нельзя изменять герб бригады"
	#define STRMSG_S_I2NOTIFY_0025 "Сейчас нельзя изменять ранг"
	#define STRMSG_S_I2NOTIFY_0026 "Дубликация ранга"
	#define STRMSG_S_I2NOTIFY_0027 "Невозможно изменение ранга командира бригады"
	#define STRMSG_S_I2NOTIFY_0028 "Изменения в ранге командира бригады невозможны."
	#define STRMSG_S_I2NOTIFY_0029 "Кол-во игроков: %dчел. (возможно максимум %dчел.)"
	#define STRMSG_S_I2NOTIFY_0030 "Добавлен в список сообщений администратора"
	#define STRMSG_S_I2NOTIFY_0031 "Удален из списка сообщений администрации"
	#define STRMSG_S_I2NOTIFY_0032 "IP сервера: %s"
	#define STRMSG_S_I2NOTIFY_0033 "Группа сервера \'%s\' всего подключено игроков: %dчел."
	#define STRMSG_S_I2NOTIFY_0034 "Вы действительно хотите закрыть сервер(%s)? номер: %d"
	#define STRMSG_S_I2NOTIFY_0035 "\'%s\'не в игре. "
	#define STRMSG_S_I2NOTIFY_0036 "Число игроков: %dчел. (возможно максимум %dчел.)"
	#define STRMSG_S_I2NOTIFY_0037 "/send %s %s"
	#define STRMSG_S_I2NOTIFY_0038 "Соответствующего отряда не существует."
	#define STRMSG_S_I2NOTIFY_0039 "Персональные сообшения разблокированы!"
	#define STRMSG_S_I2NOTIFY_0040 "Персональные сообшения заблокированы!"
	#define STRMSG_S_I2NOTIFY_0041 "Не вступил в бригаду"
	#define STRMSG_S_I2NOTIFY_0042 "Бригада(%d) недоступна"
	#define STRMSG_S_I2NOTIFY_0043 "Погода(%s)не существует"
	#define STRMSG_S_I2NOTIFY_0044 "Неверный Field Server"
	#define STRMSG_S_I2NOTIFY_0045 "Карта(%s) не существует"
	#define STRMSG_S_I2NOTIFY_0046 "Вы не можете использовать чат %d!мин."
	#define STRMSG_S_I2NOTIFY_0047 "Блокировка чата: '%10s', %3dмин."
	#define STRMSG_S_I2NOTIFY_0048 "Условия блокировки чата отменены"
	#define STRMSG_S_I2NOTIFY_0049 "Блокировка чата отменена: '%10s'"
	#define STRMSG_S_I2NOTIFY_0050 "%s(аккаунт: %s, карта: %d(%d), ур.: %d) ИГРАЕТ"
	#define STRMSG_S_I2NOTIFY_0051 "Нельзя призвать самого себя"
	#define STRMSG_S_I2NOTIFY_0052 "Данной бригады не существует"

	#define STRMSG_S_IMSERVER_050607_0001	"Данной карты не существует."
// 6_end	
///////////////////////////////////////////////////////////////////////////////
	

///////////////////////////////////////////////////////////////////////////////
// 7 - NPCServer
	// 7-1 NPC<->Field
	#define STRMSG_S_N2FIELDCONNECT_0000 "Вошел на field Server.\n"
	#define STRMSG_S_N2FIELDCONNECT_0001 "Соединение с field Server [%15s:%4d]утеряно. Повторное подключение.\r\n"

	// 7-2 IM Notify
	#define STRMSG_S_N2NOTIFY_0000 "Проверки на конфликт между монстрами и объектами не существует\r\n"
	#define STRMSG_S_N2NOTIFY_0001 "Монстр(%10s) вызван в битву за контроль над городом\r\n\r\n"

	#define STRMSG_S_N2TESTMONNAME_0000 "Монстряра"
// 7_end	
///////////////////////////////////////////////////////////////////////////////
	

///////////////////////////////////////////////////////////////////////////////
// 8 - PreServer
	// 8-1 Pre Notify
	#define STRMSG_S_P2PRENOTIFY_0000 "Выполнен вход с %s аккаунта(%s). IP: %s\r\n"
	#define STRMSG_S_P2PRENOTIFY_0001 "Успешно"
	#define STRMSG_S_P2PRENOTIFY_0002 "Не успешно"
	#define STRMSG_S_P2PRENOTIFY_0003 "[ОШИБКА] Ошибка в добавлении информации об аккаунте, AccountName(%s)  privateIP(%15s)\n"


	#define STRMSG_SCAT_051115_0001		"Здравствуйте! Вас приветствует администрация игры Аce Online."
	#define STRMSG_SCAT_051115_0002		"Приносим свои извинения за временные неудобства."
	#define STRMSG_SCAT_051115_0003		"Желаем вам приятной игры."
	#define STRMSG_SCAT_051115_0004		"Уважаемые игроки, через 30 минут будет произведена перезагрузка сервера."
	#define STRMSG_SCAT_051115_0005		"Уважаемые игроки, через 20 минут будет произведена перезагрузка сервера."
	#define STRMSG_SCAT_051115_0006		"Уважаемые игроки, через 10 минут будет произведена перезагрузка сервера."
	#define STRMSG_SCAT_051115_0007		"Уважаемые игроки, через 5 минут будет произведена перезагрузка сервера." // 5єР ИД ј­№ц БЎ°ЛАМ АЦА» ї№Б¤АФґПґЩ.
	#define STRMSG_SCAT_051115_0008		"Переместитесь в безопасные зоны остановитесь и выйдите из игры. "	// ј­№цґВ 60єР µїѕИ і»·ББъ ї№Б¤АФґПґЩ


///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

	// 2006-05-09 by cmkwon
	#define STRMSG_060509_0000			"Режим невидимости: Игроки не видят вас, а вы не можете использовать оружие."
	#define STRMSG_060509_0001			"Режим неуязвимости: Вы не получаете урона."
	#define STRMSG_060509_0002			"Стелс-режим: Монстры не могут атаковать вас первыми."

	// 2006-05-26 by cmkwon
	#define	STRMSG_060526_0000			"Ваш запрос отправлен Гейм Мастеру. Когда наш специалист получит его, он свяжется с вами."
	#define	STRMSG_060526_0001			"Не удалось автоматически обновить игру.\r\n\r\nПереустановите игру с официального сайта игры(%s) и попробуйте обновить еще раз.\r\n\r\n    Ошибка: %s"

	// 2006-08-24 by cmkwon
	#define STRMSG_060824_0000			"Данное имя не существует или имя и пароль не совпадают."
	
	// 2006-09-27 by cmkwon
	#define STRMSG_060927_0000			"На данный момент сервер отключен. Ведутся технические работы. Обратитесь к официальному сайту игры aceonline.ru для получения более подробной информации."

	// 2006-10-11 by cmkwon
	#define STRERR_061011_0000			"Неверная версия клиента.\r\n  Пожалуйста, переустановите игру."

	// 2006-11-07 by cmkwon
	#define STRMSG_061107_0000			"Вас сбил пилот %s."
	#define STRMSG_061107_0001			"\\rWarning!\\g Crossfeeding will result in a ban.\\g"


	// 2006-11-07 by cmkwon
	#define STRMSG_070410_0000   	"Инициализация базы данных сервера atum2_db_20 должна выполняться после выключения сервера."
	#define STRMSG_070410_0001   	"Вы действительно хотите перезагрузить сервер atum2_db_20- [Номер доступа:%d]"
	#define STRMSG_070410_0002   	"База данных сервера atum2_db_20 загружена."
	#define STRMSG_070410_0003   	"Базу данных сервера atum2_db_20 не удалось загрузить!"
	#define STRMSG_070410_0004   	"'%s' копирование данных в базу данных сервера atum2_db_20 завершено."
	#define STRMSG_070410_0005   	"'%s' копирование данных в базу данных сервера atum2_db_20 не завершено - персонаж не существует!"
	#define STRMSG_070410_0006   	"'%s' копирование данных в базу данных сервера atum2_db_20 не завершено - аккаунт персонажа не существует!"
	#define STRMSG_070410_0007   	"'%s' копирование данных в базу данных сервера atum2_db_20 не завершено - ошибка добавления в базу!"
	#define STRMSG_070410_0008   	"'%s' копирование данных в базу данных сервера atum2_db_20 не завершено - неизвестная ошибка (%d)!"

///////////////////////////////////////////////////////////////////////////////
// 2007-05-07 by cmkwon, ЗШ»уµµ №®АЪї­ 
	// 2007-07-24 by cmkwon, ·±ГіїЎј­ 800*600 ЗШ»уµµ »иБ¦ - ДЮєё№ЪЅє ЅєЖ®ёµ ЗКїд ѕшАЅ
	//#define STRMSG_WINDOW_DEGREE_800x600_LOW			"800x600 (низкое)"
	//#define STRMSG_WINDOW_DEGREE_800x600_MEDIUM			"800x600 (среднее)"
	//#define STRMSG_WINDOW_DEGREE_800x600_HIGH			"800x600 (высокое)"
#define STRMSG_WINDOW_DEGREE_1024x768_LOW			"1024x768 (низкое)"
#define STRMSG_WINDOW_DEGREE_1024x768_MEDIUM		"1024x768 (среднее)"
#define STRMSG_WINDOW_DEGREE_1024x768_HIGH			"1024x768 (высокое)"
#define STRMSG_WINDOW_DEGREE_W1280x800_LOW			"1280x800 (низкое - широкий экран)"
#define STRMSG_WINDOW_DEGREE_W1280x800_MEDIUM		"1280x800 (среднее - широкий экран)"
#define STRMSG_WINDOW_DEGREE_W1280x800_HIGH			"1280x800 (высокое - широкий экран)"
#define STRMSG_WINDOW_DEGREE_1280x960_LOW			"1280x960 (низкое)"
#define STRMSG_WINDOW_DEGREE_1280x960_MEDIUM		"1280x960 (среднее)"
#define STRMSG_WINDOW_DEGREE_1280x960_HIGH			"1280x960 (высокое)"
#define STRMSG_WINDOW_DEGREE_1280x1024_LOW			"1280x1024 (низкое)"
#define STRMSG_WINDOW_DEGREE_1280x1024_MEDIUM		"1280x1024 (среднее)"
#define STRMSG_WINDOW_DEGREE_1280x1024_HIGH			"1280x1024 (высокое)"
#define STRMSG_WINDOW_DEGREE_W1600x900_LOW			"1600x900 (низкое - широкий экран)"
#define STRMSG_WINDOW_DEGREE_W1600x900_MEDIUM		"1600x900 (среднее - широкий экран)"
#define STRMSG_WINDOW_DEGREE_W1600x900_HIGH			"1600x900 (высокое - широкий экран)"
#define STRMSG_WINDOW_DEGREE_1600x1200_LOW			"1600x1200 (низкое)"
#define STRMSG_WINDOW_DEGREE_1600x1200_MEDIUM		"1600x1200 (среднее)"
#define STRMSG_WINDOW_DEGREE_1600x1200_HIGH			"1600x1200 (высокое)"

// 2007-06-15 by dhjin, °ьАь °ь·Г ЅєЖ®ёµ
#define STRMSG_070615_0000		"Невозможно начать, вы не в стелс-режиме."
#define STRMSG_070615_0001		"Невозможно начать просмотр."
#define STRMSG_070620_0000	"Игрок не может начать просмотр."

// 2007-06-26 by dhjin, їцЖчАОЖ® АМєҐЖ® °ь·Г ГЯ°Ў
#define STRMSG_S_F2EVENTTYPE_0006		"Очки Войны"

// 2007-06-28 by cmkwon, БЯ±№ №жЅЙГл°ь·Г(°ФАУ ЅГ°Ј ѕЛёІ ±ёЗц) - ЅєЖ®ёµ ГЯ°Ў
#define STRMSG_070628_0000				"Вы в игре уже в течение %d ч."
#define STRMSG_070628_0001				"Вы в игре уже %d ч. Вам стоит отдохнуть."
#define STRMSG_070628_0002				"Вы играете слишком долго. Это опасно для вашего здоровья. Выйдите из игры и поспите. Ваш игровой доход будет снижен в 2 раза. "
#define STRMSG_070628_0003				"Еще чуть-чуть, и вы можете умереть от недосыпа или голода. Немедленно закройте игру и отдохните. Если вы не последуете нашему совету, ваш игровой доход снизится до 0. Ваш игровой доход вернется к обычному через 5 часов после того, как вы выйдите из игры."

///////////////////////////////////////////////////////////////////////////////
// 2007-07-11 by cmkwon, Arena block system materialization - added string
#define STRMSG_070711_0000    "\'%s\' запрещен вход на арену."
#define STRMSG_070711_0001 "\'%s\' запрещен вход на арену (осталось времени: %d мин.)"
#define STRMSG_070711_0002 "Вам запрещен вход на арену на %d мин."
#define STRMSG_070711_0003 "Запрет входа на арену снят."
#define STRMSG_070711_0004 "Использование арены запрещено игроку \'%s\'."

///////////////////////////////////////////////////////////////////////////////
// 2007-08-23 by cmkwon, Wide ЗШ»уµµ 1280x720(16:9) ГЯ°Ў - ЅєЖ®ёµ ГЯ°Ў
#define STRMSG_WINDOW_DEGREE_W1280x720_LOW			"1280x720 (низкое - широкий экран)"
#define STRMSG_WINDOW_DEGREE_W1280x720_MEDIUM		"1280x720 (среднее - широкий экран)"
#define STRMSG_WINDOW_DEGREE_W1280x720_HIGH			"1280x720 (высокое - широкий экран)"

// 2007-08-30 by cmkwon, ИёАЗ·л ЅГЅєЕЫ ±ёЗц - ЅєЖ®ёµ ГЯ°Ў
#define STRMSG_070830_0001                                   "Эту команду можно использовать только после того, как выбрана фракция."
#define STRMSG_070830_0002                                   "Карта зала совещаний(%d) данной фракции недоступна"
#define STRMSG_070830_0003                                   "Кол-во игроков, которые могут войти в зал совещаний : %dчел."
#define STRMSG_070830_0004                                   "'%s' уже добавлен в список посетителей."
#define STRMSG_070830_0005                                   "'%s' не имеет разрешения на вход."
#define STRMSG_070830_0006                                   "'%s' неправильный тип персонажа."
#define STRMSG_070830_0007                                 "'%s' не может быть добавлен в список посетителей зала совещаний.(Максимум %d чел.)"
#define STRMSG_070830_0008                                   "'%s' получил право войти в зал совещаний."
#define STRMSG_070830_0009                                   "Разрешение войти в зал совещаний получено."
#define STRMSG_070830_0010                                   "Разрешение входа в зал совещаний отменено."
#define STRMSG_070830_0011                                   "'%s'"

// 2007-11-13 by cmkwon, just for Korean service, 
#define STRMSG_071115_0001									"\\yПилот %s отправил вам подарок - %s."
#define STRMSG_071115_0002									"Список подарков: \'%s(%d ед.)\'"
#define STRMSG_071115_0003									"\\yПилот %s отправил подарок пилоту %s.  Подарок - %s. Проверьте склад."
 
// 2007-11-19 by cmkwon, callGM system 
#define STRMSG_071120_0001									"Система обращений не работает. Воспользуйтесь центром поддержки \\ysupport.4game.ru\\y"
#define STRMSG_071120_0002									"Система обращений активна."
#define STRMSG_071120_0003									"Использование системы обращений завершено."
#define STRMSG_071120_0004									"Система обращений работает с %s до %s."

// 2007-11-28 by cmkwon, ЕлБцЅГЅєЕЫ ±ёЗц - 
#define STRMSG_071128_0001									"Пилот %s отправил вам %s(%d) в качестве подарка. Проверьте ваш склад."

// 2007-12-27 by cmkwon, А©µµїмБо ёрµе ±вґЙ ГЯ°Ў - 
#define STRMSG_071228_0001				"Неверное разрешение. Проверьте настройки еще раз."

// 2008-01-31 by cmkwon, °иБ¤ єн·°/ЗШБ¦ ён·Йѕо·О °ЎґЙЗС ЅГЅєЕЫ ±ёЗц - 
#define STRMSG_080201_0001									"'Ошибка в параметрах блокировки %s'. ErrorCode(%d)"
#define STRMSG_080201_0002									"'%s' - аккаунт был заблокирован.[Block End Date: %s]"
#define STRMSG_080201_0003									"'%s' - аккаунта нет в списке заблокированных. ErrorCode(%d)"
#define STRMSG_080201_0004									"'Произошла ошибка в процессе блокирования аккаунта %s'. ErrorCode(%d)"
#define STRMSG_080201_0005									"'%s' - аккаунт был удален из списка заблокированных." 

// 2008-02-11 by cmkwon, ЗШ»уµµ ГЯ°Ў(1440x900) - 
#define STRMSG_WINDOW_DEGREE_1440x900_LOW			"1440x900 (низкое - широкий экран)"
#define STRMSG_WINDOW_DEGREE_1440x900_MEDIUM		"1440x900 (среднее - широкий экран)"
#define STRMSG_WINDOW_DEGREE_1440x900_HIGH			"1440x900 (высокое - широкий экран)"

// 2007-12-27 by dhjin, ѕЖ·№іЄЕлЗХ- ѕЖ·№іЄј­№цї¬°б°ь·ГїА·щ
#define STRMSG_S_MF2AFCONNECT_0000                       "[Error] WndProc(), Невозможно подключиться к серверу Арены [%15s:%4d] Повторное соединение\r\n"
#define STRMSG_S_MF2AFCONNECT_0001                       "Подключение к серверу Арены завершено.\r\n"
#define STRMSG_S_MF2AFCONNECT_0002                       "Подключение к серверу Арены[%15s:%4d] закрыто. Попытка повторного соединения.\r\n"
#define STRMSG_S_MF2AFCONNECT_0003                       "  T_ERROR %s(%#04X) получено от %s[%s]\r\n"
#define STRMSG_S_MF2AFCONNECT_0004                       "Unknown Error@WM_FIELD_PACKET_NOTIFY: %s(%#04x)\n"
#define STRMSG_ARENAEVENT_080310_0001                    "Number \\y%d Комнате ожидания Арены был дан атрибут эвента.\r\n"
#define STRMSG_ARENAEVENT_080310_0002                    "Number \\y%d Комната ожидания Арены лишилась атрибута эвента.\r\n"
#define STRMSG_ARENAEVENT_080310_0003                    "\\yНевозможно отдать атрибут Арены.\r\n"
#define STRMSG_080428_0001					"%s был сбит."          // 2008-04-28 by dhjin, Arena integration - String is added when taking down the opponent, only in Arena map 
#define STRERR_S_ATUMLAUNCHER_0037			"18ЁщЁщ ©цIў¬ў¬ AЎнЁщO©шaўЇў®ЎЖO AuўЇeҐмCўҐA ЎЖOAOЁцAЎЖЎМ ЁщЎѕAAA| Ёщ©шAўґAў¬Ў¤I AICIўЇЁП, CoAc ЁцAЎЖЎМўЇў®ўҐA ЎЖOAO A©ЄCaAI Ё¬OЎЖў®ўҐECOўҐIўҐU.\n\nAUЁщЁщCN ЎнcCЎїAЁ¬ ўЇў®AIЁцЁ¬ўЇAўТoAI ЎЖiЎЖўҐЁщЁъAIЎ¤I ©цўзAC©цUўТ©ЄўҐIўҐU."
#define STRMSG_120712_0001					"18ЁщЁщ ©цIў¬ў¬ AЎнЁщO©шaўЇў®ЎЖO AuўЇeҐмCўҐA ЎЖOAOЁцAЎЖЎМ ЁщЎѕAAA| Ёщ©шAўґAў¬Ў¤I AICIўЇЁП, %d Ё¬Ёў EAўЇў® ЎЖOAOAI AЁъЎ¤aҐмEўҐIўҐU."
#define STRMSG_130726_0001					"Character is already on that nation."
#define STRMSG_130726_0002					"Character is a Leader or Sub-leader, therefore cannot change nation."
#define STRMSG_130726_0003					"Character is in a Brigade; nation cannot be changed."
#define STRMSG_130726_0004					"There is no character left to change the nation."
#define STRMSG_130726_0005					"Changing nation failed [AUID(%d), CUID(%d), ToInflType(%d)] ErrorCode [%d]"
#define STRMSG_130726_0006					"Changing nation succesful [AUID(%d), CUID(%d), ToInflType(%d)]!"
#define	STRMSG_130726_0007					"Account does not exist."
#define STRMSG_130726_0008					"Account is logged in, cannot change nation."
#define STRMSG_121126_0001					"\\yWar is in progress. Crystal Trigger system has been taken offline for the duration.\\y"
#define STRMSG_121129_0001					"\\yўЇiўЇҐмAUўЇў® ACCIўЇЁП AIҐмўЇAI A|CNҐмE AoўЇЁЈ AOўҐIўҐU.\\y"
#define STRMSG_S_F2NOTIFY_0130_1			"\\cWelcome to\\c \\mDreamACE\\m: \\g%s\\g"	

// 2AЎА AIЁ¬ЎНЁЎўз

#define STRMSG_120508_0001					"%s obtains %d War Points in Lost Oasis."
#define STRMSG_120508_0002					"%s summons a boss monster in Lost Oasis!"
#define STRMSG_120508_0003					"%s activates 150%%%% increase for monster EXP (1 hour) in Lost Oasis."
#define STRMSG_120508_0004					"%s activates 150%%%% increase for item drop rate (1 hour) in Lost Oasis."
#define STRMSG_120508_0005					"%s activates 150%%%% increase for item drop rate/monster EXP/SPI (1 hur) in Lost Oasis."
#define STRMSG_120508_0006					"%s obtains Ancient Ice in Lost Oasis."
#define STRMSG_120508_0007					"%s activates Advanced Item Shop in Lost Oasis."
#define STRMSG_120508_0008					"%s activates Kit Shop in Lost Oasis."
#define STRMSG_120508_0009					"%s activates Hyper Card Shop in Lost Oasis."
#define STRMSG_120508_0010					"%s activates Weapon Shop in Lost Oasis."
#define STRMSG_120508_0011					"%s activates the warp gate to Hidden Place in Lost Oasis."

// // 2013-07-08 by jhseol, ЁЎўзў¬ўзЎЖA ЁцAЁцЁ¬AU EўзAa - STRMSG A©¬ЎЖў®
#define STRMSG_130708_0001					"\\cCommand:\\c NGC shields have been activated. Destroy the \\rNGC Controllers\\r to disable \\rGomora's\\r shields!"
#define STRMSG_130708_0002					"\\cCommand:\\c NGC Military Base defenses are down. Begin the attack!"
#define STRMSG_130708_0003					"\\cScouts:\\c \\rNGC Shield Generator\\r has been sighted."
#define STRMSG_130708_0004					"\\cScouts:\\c \\rNGC Shield Generator\\r has been destroyed."

// 2013-05-31 by jhseol,bckim ЁъЁЎў¬O AAЎ¤Ё¬ЁщC - STRMSG A©¬ЎЖў®
#define STRMSG_130531_0001					"\\g[\\g%s\\g]\\g \\gContour has been added to your Contour Collection.\\g"
#define STRMSG_130531_0002					"\\g[\\g%s\\g]\\g \\gContour has been applied [%2d] times.\\g"
#define STRMSG_130531_0003					"\\g[\\g%s\\g]\\g \\gContour has reached its maximum application. It has been changed to [%s].\\g"
#define STRMSG_130531_0004					"Your Contour has expired and stats have been removed. Your engine has been unequipped."
#define STRMSG_130531_0005					"\\yNo engine is equipped. Teleporting back to city.\\y"
#define STRMSG_130531_0006					"\\gYou cannot use the Contour currently applied to your armor.\\g"
#define STRMSG_130531_0007					"\\gContour has been changed.\\g"
#define STRMSG_130531_0008					"\\r[%s] Contour has expired.\\r"
#define STRMSG_130531_0009					"\\yArmors with Contours applied cannot be sold.\\y"
#define STRMSG_130531_0010					"\\yGEAR types do not match.\\y"

// 2013-01-21 by jhseol, NGC AuAuЎѕaAo ЁЎўзў¬ўзЎЖA ЁцAЁцЁ¬AU
#define STRMSG_130121_0001					"\\cSystem has been captured by NGC forces. Immediate evacuation has begun."
#define STRMSG_130121_0002					"\\cScouts:\\c \\rNGC Controller\\r has been confirmed."
#define STRMSG_130121_0003					"\\cScouts:\\c \\rNGC Controller\\r has been destroyed."
#define STRMSG_130121_0004					"\\cCommand:\\c \\rGomora's\\r shields are online. Destroy \\rNGC Controllers\\r to disable its shields!"
#define STRMSG_130121_0005					"\\cCommand:\\c \\rGomora's\\r shields are down! Attack now!"
#define STRMSG_130121_0006					"\\cCommand:\\c \\rGomora\\r has been destroyed! Everyone move forward!"
#define STRMSG_130121_0007					"\\cCommand:\\c \\rGomora\\r must be destroyed first."
#define STRMSG_130121_0008					"\\c[%s] activated by \\c\\rNGC Controller\\r overload."
#define STRMSG_130121_0009					"\\y[NGC Outpost Base System]\\y."

// 2008-04-29 by cmkwon, ј­№ц±є Б¤єё DBїЎ ГЯ°Ў(ЅЕ±Ф °иБ¤ ДіёЇЕН »эјє Б¦ЗС ЅГЅєЕЫГЯ°Ў) - 
#define STRMSG_080430_0001					"На выбранном сервере создание новых персонажей недоступно."

// 2008-06-13 by dhjin, EP3 ї©ґЬ јцБ¤ »зЗЧ - 
#define STRMSG_080613_0001					"Запрос на вступление в бригаду %s был отклонён."

// 2008-09-04 by cmkwon, don't need translation, SystemLog 
#define STRMSG_080904_0001					 "[DB Error] Отсутствует функция обработки(QP_xxx) запроса БД !! QueryType(%d:%s)\r\n"


// 2008-12-30 by cmkwon, БцµµАЪ Г¤ЖГ Б¦ЗС Д«µе ±ёЗц - 
#define STRMSG_081230_0001					"\\yЧат персонажа %s был заблокирован на %d минут.\\y"
#define STRMSG_081230_0002					"\\yЧат был заблокирован лидером на %d минут.\\y" 
#define STRMSG_081230_0003					"\\yБлокировка чата лидером снята.\\y"
#define STRMSG_081230_0004					"Not enough Money for chatting. You need at least %d SPI to use this chat!"

///////////////////////////////////////////////////////////////////////////////
// 2009-08-31 by cmkwon, Gameforge4D °ФАУ°Ўµе µїАЗГў ¶зїм±в - 
// 2009-09-02 by cmkwon, Gameforge4D °ФАУ °Ўµе µїАЗГў WebPage·О Гіё® - »зїлЗПБц ѕКАЅ, STRMSG_090831_0001ґВ АҐЖдАМБц·О Гіё®
//#define STRMSG_090831_0001					"AirRivals is now protected from cheaters with a hackshield.\r\nPlease install it to help us to make AirRivals even safer.\r\nYou can only continue gameplay once you have installed the hackshield.\r\nPlease read the privacy policy< http://agb.gameforge.de/mmog/index.php?lang=en&art=datenschutz_mmog&special=airrivals&&f_text=b1daf2&f_text_hover=ffffff&f_text_h=061229&f_text_hr=061229&f_text_hrbg=061229&f_text_hrborder=9EBDE4&f_text_font=arial%2C+arial%2C+arial%2C+sans-serif&f_bg=000000 > to find out more about the hackshield's function."
#define STRMSG_090831_0002					"Install hackshield"
#define STRMSG_090831_0003					"cancel"

///////////////////////////////////////////////////////////////////////////////
// 2009-09-02 by cmkwon, Gameforge4D °ФАУ °Ўµе µїАЗГў WebPage·О Гіё® - 
#define STRMSG_090902_0001					"http://www.airrivals.net/launcher/hackshield.html"

///////////////////////////////////////////////////////////////////////////////
// 2009-10-16 by cmkwon, Бцїш ЗШ»уµµ ГЯ°Ў(1680x1050,1920x1080,1920x1200) - 
#define STRMSG_WINDOW_DEGREE_1680x1050_LOW			"1680x1050 (low)"
#define STRMSG_WINDOW_DEGREE_1680x1050_MEDIUM		"1680x1050 (medium)"
#define STRMSG_WINDOW_DEGREE_1680x1050_HIGH			"1680x1050 (high)"
#define STRMSG_WINDOW_DEGREE_1920x1080_LOW			"1920x1080 (low)"
#define STRMSG_WINDOW_DEGREE_1920x1080_MEDIUM		"1920x1080 (medium)"
#define STRMSG_WINDOW_DEGREE_1920x1080_HIGH			"1920x1080 (high)"
#define STRMSG_WINDOW_DEGREE_1920x1200_LOW			"1920x1200 (low)"
#define STRMSG_WINDOW_DEGREE_1920x1200_MEDIUM		"1920x1200 (medium)"
#define STRMSG_WINDOW_DEGREE_1920x1200_HIGH			"1920x1200 (high)"
#define STRMSG_WINDOW_DEGREE_3440x1440_LOW			"3440x1440 (low)"
#define STRMSG_WINDOW_DEGREE_3440x1440_MEDIUM		"3440x1440 (medium)"
#define STRMSG_WINDOW_DEGREE_3440x1440_HIGH			"3440x1440 (high)"


// Rovenia update
#define STRMSG_AUTHENTICATION_ACCEPT_COMMENT_NOT_REGISTER "Сервер не зарегистрирован (возможно, это пиратский сервер)."	
#define STRMSG_AUTHENTICATION_ACCEPT_COMMENT_DB_ERROR "Ошибка при связи с базой данных."	
#define STRMSG_AUTHENTICATION_ACCEPT_COMMENT_OK "Вы авторизованы."	
#define STRMSG_AUTHENTICATION_ACCEPT_COMMENT_BLOCKED "IP сервера зарегистрирован, но в доступе отказано."
#define STRMSG_AUTHENTICATION_ACCEPT_COMMENT_SHUTDOWN				"Команда завершения работы Windows отправлена на сервер."

// 2014-03-18 by bckim, ў¬ўТAI ON/OFF
#define STRMSG_130318_0003					"\\yYou can't use the trade shop at the moment.\\y"
// End. 2014-03-18 by bckim, ў¬ўТAI ON/OFF

#define STRMSG_KILL_0001					"%s has been shot down. Reward %d SPI %d WP"
///////////////////////////////////////////////////////////////////////////////
// 2012-03-30 by hskim, EP4 Ж®ё®°Е ЅГЅєЕЫ АМєҐЖ® ѕЛёІ
#define STRMSG_120330_0001					"%sАМ ѕЦЅ¬·№АОїЎј­ јы°ЬБш °ш°Ј їцЗБ °ФАМЖ®ё¦ №Яµї ЗПїґЅАґПґЩ."
#define STRMSG_120330_0002					"%sАМ ѕЦЅ¬·№АОїЎј­ ёуЅєЕН °жЗиДЎ 100%%%% Бх°Ў ЗШЗЗѕЖїц АМєҐЖ®(1ЅГ°Ј)ё¦ №Яµї ЗПїґЅАґПґЩ."
#define STRMSG_120330_0003					"%sАМ ѕЦЅ¬·№АОїЎј­ ѕЖАМЕЫ µе·УАІ 100%%%% Бх°Ў ЗШЗЗѕЖїц АМєҐЖ®(1ЅГ°Ј)ё¦ №Яµї ЗПїґЅАґПґЩ."
#define STRMSG_120330_0004					"%sАМ ѕЦЅ¬·№АОїЎј­ ѕЖАМЕЫ µе·УАІ 100%%%% / ёуЅєЕН °жЗиДЎ 100%%%% Бх°Ў / SPI·® 100%%%% Бх°Ў ЗШЗЗѕЖїц АМєҐЖ®(1ЅГ°Ј)ё¦ №Яµї ЗПїґЅАґПґЩ."
#define STRMSG_120330_0005					"%sґФАМ ѕЦЅ¬·№АОїЎј­ №«±в »уБЎА» №Яµї ЗПїґЅАґПґЩ."
#define STRMSG_120330_0006					"%sґФАМ ѕЦЅ¬·№АОїЎј­ ЗПАМЖЫ Д«µе »уБЎА» №Яµї ЗПїґЅАґПґЩ."
#define STRMSG_120330_0007					"%sґФАМ ѕЦЅ¬·№АОїЎј­ Е°Ж® »уБЎА» №Яµї ЗПїґЅАґПґЩ."
#define STRMSG_120330_0008					"%sґФАМ ѕЦЅ¬·№АОїЎј­ ґлЗь ёуЅєЕНё¦ јТИЇЗПјМЅАґПґЩ."
#define STRMSG_120330_0009					"Е©ё®ЅєЕ»АМ јТёкЗПїґЅАґПґЩ."

#endif // end_#ifndef _STRING_DEFINE_SERVER_H_
