#if !defined(AFX_SCDIALER2_H__7012CCA9_EEC6_49AC_B4F9_81BBDE6648EC__INCLUDED_)
#define AFX_SCDIALER2_H__7012CCA9_EEC6_49AC_B4F9_81BBDE6648EC__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSCDialer2 wrapper class

class CSCDialer2 : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSCDialer2)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xadaa5f78, 0xb23, 0x4c82, { 0xb4, 0xd, 0x9a, 0x54, 0x7b, 0x2f, 0x90, 0x49 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetStrVDServerIP();
	void SetStrVDServerIP(LPCTSTR);
	long GetUsVDServerPort();
	void SetUsVDServerPort(long);
	long GetNStatus();
	void SetNStatus(long);
	BOOL GetAudioSendPause();
	void SetAudioSendPause(BOOL);

// Operations
public:
	long JoinRoom(LPCTSTR szUserName, long* pn64RoomID);
	void GoOutRoom();
	long CreateRoom(LPCTSTR szUserName, long* pn64RoomID);
	long CreateRoomEx(LPCTSTR i_szUserName, long* i_pn64RoomID, long i_nConcurrentTalkingCount);
	long SetSpkVolume(long i_nVolumeValueOfPercent);
	long GetSpkVolume();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SCDIALER2_H__7012CCA9_EEC6_49AC_B4F9_81BBDE6648EC__INCLUDED_)
