#if !defined(AFX_SCDIALER1_H__690F80E6_3746_4E5E_971F_A602EF346461__INCLUDED_)
#define AFX_SCDIALER1_H__690F80E6_3746_4E5E_971F_A602EF346461__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSCDialer1 wrapper class

class CSCDialer1 : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSCDialer1)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xe43303fe, 0xbde8, 0x44e2, { 0x87, 0xbf, 0x25, 0x9d, 0x92, 0xf, 0x3a, 0xdd } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetPCCallAgentIP();
	void SetPCCallAgentIP(LPCTSTR);
	long GetPCCallAgentPort();
	void SetPCCallAgentPort(long);
	CString GetUserID();
	void SetUserID(LPCTSTR);
	CString GetPhoneNumber();
	void SetPhoneNumber(LPCTSTR);
	CString GetPcn();
	void SetPcn(LPCTSTR);
	BOOL GetAutoAcceptCall();
	void SetAutoAcceptCall(BOOL);
	BOOL GetEnableTelBox();
	void SetEnableTelBox(BOOL);
	long GetProxyMode();
	void SetProxyMode(long);
	short GetStatus();
	void SetStatus(short);
	CString GetPhoneBookList();
	void SetPhoneBookList(LPCTSTR);
	short GetAuthType();
	void SetAuthType(short);
	BOOL GetDialButtonClicked();
	void SetDialButtonClicked(BOOL);
	short GetMyStatus();
	void SetMyStatus(short);
	BOOL GetDTMFWave();
	void SetDTMFWave(BOOL);
	BOOL GetRingWave();
	void SetRingWave(BOOL);
	BOOL GetInBand();
	void SetInBand(BOOL);
	CString GetLKey();
	void SetLKey(LPCTSTR);
	CString GetWebCallAgentIP();
	void SetWebCallAgentIP(LPCTSTR);
	long GetWebCallAgentPort();
	void SetWebCallAgentPort(long);
	short GetCallType();
	void SetCallType(short);
	short GetDeviceType();
	void SetDeviceType(short);
	short GetSerialPort();
	void SetSerialPort(short);
	short GetAutoRetryLoginInterval();
	void SetAutoRetryLoginInterval(short);
	CString GetPlayDevice();
	void SetPlayDevice(LPCTSTR);
	CString GetRecordDevice();
	void SetRecordDevice(LPCTSTR);
	CString GetWaveDevice();
	void SetWaveDevice(LPCTSTR);
	long GetNATServerPort();
	void SetNATServerPort(long);
	long GetNATFireTalkPort();
	void SetNATFireTalkPort(long);
	BOOL GetManualRoute();
	void SetManualRoute(BOOL);

// Operations
public:
	BOOL Hangup(short Mode);
	BOOL RegisterServer(short Mode);
	BOOL UnRegisterServer();
	BOOL AcceptCall(short IsAccept);
	BOOL SetLicenseKey(LPCTSTR LicenseKey);
	void SpkVolumeUp();
	void SpkVolumeDown();
	void MicVolumeUp();
	void MicVolumeDown();
	void PushButton(LPCTSTR button);
	BOOL IsRegistered();
	BOOL RetrievePhoneBook();
	void GetAudioDeviceList();
	void Forwarding(short Type, LPCTSTR Destination);
	void SendVideoInfo(LPCTSTR IP, long Port);
	BOOL SendMessage(LPCTSTR Destination, LPCTSTR Message);
	long SerialMessage(long dwMsg);
	long TimeOutTone();
	void Dial();
	void ReDial();
	CString GetVersion();
	void SendVideoPause(long Flag);
	void SetKeepAliveSerial(LPCTSTR KeepAlive);
	void MakeConference(short AttendantCount, LPCTSTR ConferenceInfo);
	void JoinConference(LPCTSTR ConferenceID, LPCTSTR ConferenceInfo);
	void InviteConference(LPCTSTR Callee);
	void CloseConference();
	void StatusConference(short Status, LPCTSTR StatusInfo);
	void LeaveConference();
	long SetSpkVolume(long i_nVolumeValueOfPercent);
	long GetSpkVolume();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SCDIALER1_H__690F80E6_3746_4E5E_971F_A602EF346461__INCLUDED_)
